### ISSUE TITLE
Inconveniences running in root

### ISSUE THREAD

**Issue by selipso** [yeoman/yo#216]
```
root@6b10c5a8673c:/var/test# yo angular-fullstack:route about
? Where would you like to create this route? (client/app/) 
/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/configstore.js:55
                throw err;
                      ^
Error: EACCES, permission denied '/root/.config/configstore/insight-yo.yml'
You don't have access to this file.

    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.create.all.get (/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/configstore.js:33:29)
    at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/configstore.js:26:44)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:26:34)
    at process.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/insight/lib/push.js:11:16)
    at process.emit (events.js:98:17)
    at handleMessage (child_process.js:322:10)
    at Pipe.channel.onread (child_process.js:349:11)
? Where would you like to create this route? client/app/
? What will the url of your route be? /about
   create client/app/about/about.js

/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/node_modules/mkdirp/index.js:89
                    throw err0;
                          ^
Error: EACCES, permission denied '/var/test/client/app/about'
    at Object.fs.mkdirSync (fs.js:653:18)
    at Function.sync (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/node_modules/mkdirp/index.js:70:13)
    at Generator.<anonymous> (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/actions/actions.js:214:14)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
root@6b10c5a8673c:/var/test# 
```

I was originally going to submit this as a bug, but I think preventing this EACCESS error would go a long way towards making yo headache-free. I don't want to have to clear my .config/configstores each time. I use docker containers for building and testing so I unfortunately encounter this very frequently. Thanks for your consideration!

**Comment by OKNoah** [comment]
I have this issue without Docker. I am on Ubuntu 14.04 using the root user.
