### ISSUE TITLE
Navigating yo menu with arrow keys throws an error

### ISSUE THREAD

**Issue by mattinteractive** [yeoman/yo#249]
Apologies if this is inappropriate to post here, but I'm trying to learn me some Yeoman. I've got the environment all installed. When I try to use my arrow keys to pick a generator, this error gets thrown:

`/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:9229
        throw e;
              ^
ReferenceError: parent is not defined
    at AnonymousObserver._onNext (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:4259:63)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1863:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1795:35)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:9226:23)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1795:35)
    at Subject.Rx.Subject.addProperties.onNext`

and FYI, I've tried uninstalling and reinstalling node, yo, etc.

**Comment by addyosmani** [comment]
@mattinteractive This is no longer showing up as an issue for me locally in yo 1.3.3. Can we close this or are you still running into this problem?

**Comment by adamarthurryan** [comment]
FYI - Number keys will allow menu navigation, even if the arrow keys don't work.
