### ISSUE TITLE
"Update your generators" throws error in rx.js

### ISSUE THREAD

**Issue by markrendle** [yeoman/yo#285]
Running `yo` outside any project directory and choosing "Update your generators" throws an error, thus:

```
/usr/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:9379
        throw e;
              ^
TypeError: Object #<Object> has no method 'map'
    at module.exports (/usr/lib/node_modules/yo/lib/routes/update.js:30:37)
    at Router.navigate (/usr/lib/node_modules/yo/lib/router.js:36:30)
    at PromptUI.completed (/usr/lib/node_modules/yo/lib/routes/home.js:83:11)
    at PromptUI.onCompletion (/usr/lib/node_modules/yo/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1965:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1902:14)
    at AutoDetachObserverPrototype.completed (/usr/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:9397:23)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1902:14)
    at AnonymousObserver._onCompleted (/usr/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:3032:49)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1965:12)
```

System info:
```
1.4.4
/home/mark/.kre/packages/KRE-Mono.1.0.0-beta2/bin:/home/mark/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/mark/bin:/home/mark/go/bin /usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
linux { http_parser: '1.0',
  node: '0.10.35',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.30',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1j' }
```

**Comment by sindresorhus** [comment]
`npm i -g yo` to fix ;)
