### ISSUE TITLE
yo reveal:slide breaks on yo@1.4.5

### ISSUE THREAD

**Issue by dvberkel** [yeoman/yo#286]
I am not sure this is a problem with yo, so I am cross reporting this issue also to the [generator-reveal][] plugin.

When running a yo command it told me that a new version was available. The version I was using was `1.3.3` and the latest version was `1.4.5`. I upgraded with the command `npm install --global yo`. When I did the `yo reveal:slide` command stop working.

In particular the following command
```sh
yo reveal:slide --markdown "broken"
```
produces the following error
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Did not provide required argument name!
    at SlideGenerator.<anonymous> (/usr/local/lib/node_modules/generator-reveal/node_modules/yeoman-generator/lib/base.js:351:33)
    at Array.forEach (native)
    at SlideGenerator.Base.checkRequiredArgs (/usr/local/lib/node_modules/generator-reveal/node_modules/yeoman-generator/lib/base.js:347:19)
    at SlideGenerator.argument (/usr/local/lib/node_modules/generator-reveal/node_modules/yeoman-generator/lib/base.js:317:8)
    at SlideGenerator.module.exports.Base.extend.constructor (/usr/local/lib/node_modules/generator-reveal/node_modules/yeoman-generator/lib/named-base.js:20:10)
    at new SlideGenerator (/usr/local/lib/node_modules/generator-reveal/slide/index.js:17:51)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:281:10)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:258:15)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:317:24)
    at /usr/local/lib/node_modules/yo/lib/cli.js:91:9
```

only when I downgraded yo to version 1.3.3 did the command produce the expected result.

[generator-reveal]: https://github.com/slara/generator-reveal/issues/64

**Comment by SBoudrias** [comment]
Here's your error `Did not provide required argument name!`

It expect you to provide an argument for the slide name. My guess is before we parsed "broken" as the name, but the way you write it, it actually is parsed as the value of `markdown` option.
