### ISSUE TITLE
When use yo react-material-ui raise error

### ISSUE THREAD

**Issue by lastjune** [yeoman/yo#309]
when i use yo react-material-ui it raise an error,

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Did not provide required argument apptitle!
    at null.<anonymous> (/usr/local/lib/node_modules/generator-react-material-ui/node_modules/yeoman-generator/lib/base.js:351:33)
    at Array.forEach (native)
    at Base.checkRequiredArgs (/usr/local/lib/node_modules/generator-react-material-ui/node_modules/yeoman-generator/lib/base.js:347:19)
    at argument (/usr/local/lib/node_modules/generator-react-material-ui/node_modules/yeoman-generator/lib/base.js:317:8)
    at new module.exports.generators.Base.extend.constructor (/usr/local/lib/node_modules/generator-react-material-ui/app/index.js:9:10)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:282:10)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:259:15)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:318:24)
    at /usr/local/lib/node_modules/yo/lib/cli.js:86:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)

I have tried to update yo and generator react-material-ui, also clean cache.

still get the same error.

**Comment by SBoudrias** [comment]
> Did not provide required argument apptitle!

**Comment by lastjune** [comment]
Hi @SBoudrias ,thank you.

Actually, i was type yo in the terminal and choose the generator, and pick some dependecies in the beginngin, and i get error, so then i tried use "yo react-material-ui".

In the terminal, use yo react-material-ui mui , it works.
But if i just type yo, and then choose the React Material Ui, it raise error.

/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:580
    throw e;
          ^
Error: Did not provide required argument apptitle!
    at null.<anonymous> (/usr/local/lib/node_modules/generator-react-material-ui/node_modules/yeoman-generator/lib/base.js:351:33)
    at Array.forEach (native)
    at Base.checkRequiredArgs (/usr/local/lib/node_modules/generator-react-material-ui/node_modules/yeoman-generator/lib/base.js:347:19)
    at argument (/usr/local/lib/node_modules/generator-react-material-ui/node_modules/yeoman-generator/lib/base.js:317:8)
    at new module.exports.generators.Base.extend.constructor (/usr/local/lib/node_modules/generator-react-material-ui/app/index.js:9:10)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:282:10)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:259:15)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:318:24)

How can i give apptitle with this process?

**Comment by SBoudrias** [comment]
There's no way to pass arguments or options using only `yo`. The only way when arguments or options are requirement is to run them as `yo <name> <arguments> --options`

**Comment by lastjune** [comment]
Okay, thanks.
