### ISSUE TITLE
EACCES, permission denied please help me fix this issue

### ISSUE THREAD

**Issue by YonasBerhe** [yeoman/yo#313]
Can't run the Yo command as root user. 
root@yonas:/home/yonas# yo
/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:56
				throw err;
				      ^
Error: EACCES, permission denied '/root/.config/configstore/insight-yo.yml'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:500:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:352:15)
    at Object.create.all.get (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:36:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:117:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

**Comment by SBoudrias** [comment]
google `chmod`

**Comment by kevva** [comment]
Also, Google the error message you're getting. There are several issues opened about it in this repo too.
