### ISSUE TITLE
yo mocha > Error: Cannot find module 'tough-cookie'

### ISSUE THREAD

**Issue by crgomo** [yeoman/yo#320]
When trying to run the command `yo mocha` throws the following error:

```bash
 yo mocha
module.js:338
    throw err;
    ^
Error: Cannot find module 'tough-cookie'
```

The same happens when installing a generator: `$ yo webapp`

```bash
Out of the box I include HTML5 Boilerplate, jQuery, and a Gruntfile.js to build your app.
? What more would you like? Bootstrap
   create Gruntfile.js
   create package.json
   create .gitignore
   create .gitattributes
   create .bowerrc
   create bower.json
   create .jshintrc
   create .editorconfig
   create app/styles/main.css
   create app/favicon.ico
   create app/robots.txt
   create app/index.html
   create app/scripts/main.js
module.js:338
    throw err;
    ^
Error: Cannot find module 'tough-cookie'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-mocha/node_modules/yeoman-generator/node_modules/request/lib/cookies.js:3:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

This is the result requested at your webpage for opening an issue.

```bash
$ yo --version && echo $PATH $NODE_PATH && node -e 'console.log(process.platform, process.versions)' && cat Gruntfile.js
1.4.6
./node_modules/.bin:/Users/username/bin:./node_modules/.bin:/Users/username/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
darwin { http_parser: '2.3',
  node: '0.12.2',
  v8: '3.28.73',
  uv: '1.4.2-node1',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1m' }
cat: Gruntfile.js: No such file or directory
```

Hope somebody can help me, thanks.

**Comment by SBoudrias** [comment]
That's an issue with the [request](https://github.com/request/request/issues) module. Please open an issue over there.
