### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Longtete** [yeoman/yo#323]
/usr/lib/node_modules/generator-meanjs/node_modules/yeoman-generator/node_modules/mkdirp/index.js:89
                    throw err0;
                          ^
Error: EACCES, permission denied '/root/public/modules'
    at Object.fs.mkdirSync (fs.js:654:18)
    at Function.sync (/usr/lib/node_modules/generator-meanjs/node_modules/yeoman-generator/node_modules/mkdirp/index.js:70:13)
    at yeoman.generators.Base.extend.copyApplicationFolder (/usr/lib/node_modules/generator-meanjs/app/index.js:124:8)
    at /usr/lib/node_modules/generator-meanjs/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:354:15)

**Comment by SBoudrias** [comment]
> permission denied '/root/public/modules'
