### ISSUE TITLE
EACCES, permission denied

### ISSUE THREAD

**Issue by Narjhanam** [yeoman/yo#331]
Hey,
I installed 'yo' earliear gloably using npm, as root.
This is a test vm server, when I run it I got the following error

```
Error: EACCES, permission denied '/root/.config/configstore/insight-yo.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:427:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:284:15)
    at Object.create.all.get (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:36:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:117:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

I created a regular user and tested yo , it worked as expected. 
But I'm interested to know why It didn't work as root as I don't want to use another user.

Cheers,

**Comment by kevva** [comment]
https://github.com/yeoman/yeoman.io/issues/282 https://github.com/yeoman/yeoman/issues/1097
