### ISSUE TITLE
insight-yo.json

### ISSUE THREAD

**Issue by lizhengnacl** [yeoman/yo#348]
run <code>yo webapp</code>, and the err show:
```
Error: EACCES, permission denied '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at Object.fs.readFileSync (fs.js:354:15)
    at Object.create.all.get (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:27:26)
    at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:20:44)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:130:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

when I run the command<code>ls /root/.config/configstore</code>, the result is:
```
bower-github.yml  insight-bower.yml  update-notifier-bower.yml
```
HELP !!

**Comment by arthurvr** [comment]
That's a permission error coming from configstore. There's not much we can do about that, except [throwing a better error message](https://github.com/yeoman/configstore/issues/6). For now you should be able to fix it using the `chmod` command in the issue.

**Comment by SBoudrias** [comment]
Also, note that it's weird the file appear into `/root/`. This mean you've been running commands as `sudo`. The take away here is you should never run anything as `sudo`, it's very unsecure and is just creating issues. Ensure your main user have the correct permissions on your system.

**Comment by lizhengnacl** [comment]
@arthurvr @SBoudrias
thx~
I have resolved the problem on the root cause by using [NVM](https://github.com/creationix/nvm), It's really really great.

**Comment by arthurvr** [comment]
Oh, yes it is! NVM isn't specifically about issues like this but it's a perfectly valid fix. Glad it's resolved!

**Comment by minicloud** [comment]
+

**Comment by looeee** [comment]
Bump on this issue as I have been unable to solve it using permissions (the directory does not exist) or nvm

/home/projects/yo-test# yo
/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:53
                                throw err;
                                ^

Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.create.all.get (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:130:11)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)

**Comment by SBoudrias** [comment]
@looeee it is permissions issues. To change permissions, you need to have permission to change them. So you need to `sudo chmod ....`

**Comment by looeee** [comment]
As I said, the directory and files do not actually exist so this doesn't work. Nonetheless I tried actually creating the directory file and chmod 777 on it just as a test, this also didn't work (same error). 
Anyway I decided to just install locally which works fine.

**Comment by RangerRick** [comment]
I'm seeing the same issue.  Fresh install, running as root.  Everything in node was installed as root (not just 'sudo', actual root), and running (in my case) `yo hubot` fails with a permission denied.

If I create the directory it still fails:

```
root@chat:/opt/hubot# ls -la /root/.config/configstore/
total 8
drwxr-xr-x 2 root root 4096 Dec  1 15:44 .
drwxr-xr-x 3 root root 4096 Dec  1 15:44 ..
root@chat:/opt/hubot# yo hubot
/usr/local/node-v5.1.0-linux-x64/lib/node_modules/yo/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.create.all.get (/usr/local/node-v5.1.0-linux-x64/lib/node_modules/yo/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/local/node-v5.1.0-linux-x64/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/node-v5.1.0-linux-x64/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/local/node-v5.1.0-linux-x64/lib/node_modules/yo/lib/cli.js:130:11)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
```

**Comment by SBoudrias** [comment]
@RangerRick don't install anything as sudo - ever. Doing this is a huge security risk.

**Comment by royling** [comment]
I got this issue when running yo in a container, thanks to this discussion, I solved the problem by `RUN useradd` in Dockerfile :bow:

**Comment by dreamerkumar** [comment]
royling is there anything that can be done on the command line after I ssh into my docker container to fix this issue?

**Comment by royling** [comment]
@dreamerkumar yes, you can add user after ssh and switch to it (`su - docker`), it's just equivalent to do so in the Dockerfile as below:
```
RUN useradd -ms /bin/bash docker
USER docker
```

**Comment by gimoh** [comment]
Just in case you are installing in a container and you know what you're doing, you can also do:

    sed -i -e '/rootCheck/d' "${NPM_CONFIG_PREFIX}/lib/node_modules/yo/lib/cli.js"

freedom FTW!

see also sindresorhus/root-check#1

**Comment by iruoma** [comment]
@RangerRick  hi, i know this is years later, but am wondering how u were able to solve this issue. I am running into the same error and I have no idea what to do. I have tried several suggestions but nothing seems to be working.
I would really appreciate your help. Thank you

**Comment by RangerRick** [comment]
@iruoma Sorry, I honestly have not used this for a long time, I'm no help.

**Comment by iruoma** [comment]
thank you so much... i eventually figured it out.

**Comment by Code-Egg** [comment]
@iruoma So, how to fix this??

**Comment by iruoma** [comment]
Hi,
Sorry for the late response. I figured out that yo doesn't work as a root
user. So i just created another user on linux and ran yo and it worked
without any issues. You can make use of sudo or give the new user root
priivileges.
I hope this works for you.

**Comment by yangqingxian** [comment]
Do not run the yo command as `root`.

**Comment by xahon** [comment]
I'm going to remove yo due to same issue

**Comment by radhatdcx** [comment]
@lizhengnacl 
Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Configstore.get (/usr/local/nodejs/node-v6.11.3-linux-x64/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:34:26)
    at Configstore.get (/usr/local/nodejs/node-v6.11.3-linux-x64/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:81:14)
    at Insight.get (/usr/local/nodejs/node-v6.11.3-linux-x64/lib/node_modules/yo/node_modules/insight/lib/index.js:48:22)
    at Object.<anonymous> (/usr/local/nodejs/node-v6.11.3-linux-x64/lib/node_modules/yo/lib/cli.js:194:48)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

what this problem solved for NVM ？？？

**Comment by TristanPeers** [comment]
For anybody running into this issue in docker using alpine, I fixed it using the great sed command above from @gimoh:

```
# Install hubot
RUN npm install -g yo generator-hubot
RUN sed -i -e '/rootCheck/d' "/usr/local/lib/node_modules/yo/lib/cli.js" \
  && mkdir /opt/hubot \
  && cd /opt/hubot \
  && yo hubot
```

**Comment by Llorx** [comment]
Small machine that I don't care, so I'm using everything as root, so avoid the "do not run as root" comments as a fix, as that's not a fix, but a workaround.

I ran `chmod 777 -R /root/*`, and still having this problem. Pretty weird.

**Comment by vyychenyy** [comment]
> Just in case you are installing in a container and you know what you're doing, you can also do:
> 
> ```
> sed -i -e '/rootCheck/d' "${NPM_CONFIG_PREFIX}/lib/node_modules/yo/lib/cli.js"
> ```
> freedom FTW!
> 
> see also [sindresorhus/root-check#1](https://github.com/sindresorhus/root-check/issues/1)

thx!!issue is resolved!

**Comment by SugarGuan** [comment]
> 这个问题怎么用nvm 解决的？？

同问啊 嘿嘿

**Comment by SugarGuan** [comment]
Would like to ask that 
how to use _nvm_ to slove this question ..
