### ISSUE TITLE
yo is not working

### ISSUE THREAD

**Issue by zeroion** [yeoman/yo#355]
the yo is not working since I upgraded.

```sh
$ yo
module.js:338
    throw err;
          ^
Error: Cannot find module 'yeoman-environment'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:63:13)
    at pre (/usr/local/lib/node_modules/yo/lib/cli.js:59:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:153:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```
Versions is...
```sh
$ node --version
v0.12.7
$ npm --version
2.13.4
$ yo --version
1.4.7
```

**Comment by SBoudrias** [comment]
Looks like an installation error. Please remove and reinstall.
