### ISSUE TITLE
Error when using 'yo' - node v4.1.1

### ISSUE THREAD

**Issue by tabone** [yeoman/yo#365]
I am trying to use `yo` but the following error is being thrown.

```
Lucas-MacBook-Pro:x tabone$ nvm use node
Now using node v4.1.1 (npm v2.14.4)
Lucas-MacBook-Pro:x tabone$ yo
/Users/tabone/.nvm/versions/node/v4.1.1/lib/node_modules/yo/node_modules/meow/node_modules/trim-newlines/index.js:8
	return x.replace(/^[\r\n]+/, '');
	         ^

TypeError: x.replace is not a function
    at Function.fn.start (/Users/tabone/.nvm/versions/node/v4.1.1/lib/node_modules/yo/node_modules/meow/node_modules/trim-newlines/index.js:8:11)
    at module.exports (/Users/tabone/.nvm/versions/node/v4.1.1/lib/node_modules/yo/node_modules/meow/node_modules/trim-newlines/index.js:4:19)
    at module.exports (/Users/tabone/.nvm/versions/node/v4.1.1/lib/node_modules/yo/node_modules/meow/index.js:33:20)
    at Object.<anonymous> (/Users/tabone/.nvm/versions/node/v4.1.1/lib/node_modules/yo/lib/cli.js:15:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
```

Failed to replicate it on node v4.0.0.

```
Lucas-MacBook-Pro:x tabone$ nvm use v4.0.0
Now using node v4.0.0 (npm v2.14.2)
Lucas-MacBook-Pro:x tabone$ yo
? 'Allo Luca! What would you like to do? (Use arrow keys)
  Run a generator
❯ Test 
  ──────────────
  Update your generators 
  Install a generator 
  Find some help 
  Get me out of here! 
  ──────────────
```

**Comment by sindresorhus** [comment]
Fixed in a sub-dependency. Just reinstall `yo`. Sorry about that.
