### ISSUE TITLE
"yo" EACCES error permission denied

### ISSUE THREAD

**Issue by N3TC4T** [yeoman/yo#368]
just installed **yo** with **npm** and everthing was fine . but in running yo i get this error 

> /root/.nvm/versions/node/v4.1.2/lib/node_modules/yo/node_modules/configstore/index.js:62
				throw err;
				^
Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json.4569dd18d20892f783f86378d42e6084'
You don't have access to this file.
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1161:15)
    at Function.writeFileSync [as sync] (/root/.nvm/versions/node/v4.1.2/lib/node_modules/yo/node_modules/configstore/node_modules/write-file-atomic/index.js:37:12)
    at Object.create.all.set (/root/.nvm/versions/node/v4.1.2/lib/node_modules/yo/node_modules/configstore/index.js:55:21)
    at Object.Configstore (/root/.nvm/versions/node/v4.1.2/lib/node_modules/yo/node_modules/configstore/index.js:20:11)
    at new Insight (/root/.nvm/versions/node/v4.1.2/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/root/.nvm/versions/node/v4.1.2/lib/node_modules/yo/lib/cli.js:128:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

There is something I can't understand is i have only one user and it's is **root** and both installation and running did with **root** and I've checked all files permissions and everything is ok .

**Comment by N3TC4T** [comment]
Ok issues fixed with [this](https://github.com/yeoman/yeoman.github.io/issues/282#issuecomment-64543114)

**Comment by MaheshHT** [comment]
Create another user and run command yo hubot  in newly creaed user will work.
