### ISSUE TITLE
mac os sudo npm install -g yo

### ISSUE THREAD

**Issue by zanjs** [yeoman/yo#369]
zandeMacBook-Pro:react-yo zan$ yo --help
-bash: /usr/local/bin/yo: No such file or directory

**Comment by sindresorhus** [comment]
Google the error message. This has nothing to do with `yo`, but rather installing with `npm` and your system.

**Comment by zanjs** [comment]
thinks you

**Comment by zanjs** [comment]
zandeMacBook-Pro:bin zan$ ls
apm                browser-sync       github             node               npm                pstorm             webpack
atom               flow               grunt              node-dev           pcre-config        react-native       wstorm
bower              git-lfs            gulp               node-sass          pcregrep           react-native-start yo
brew               gitbook            jspm               node-scss-lint     pcretest           watchman
zandeMacBook-Pro:bin zan$ 


👌

**Comment by zanjs** [comment]
zandeMacBook-Pro:react-yo zan$  yo react-webpack
/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:46
                throw err;
                ^

Error: EACCES: permission denied, open '/Users/zan/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.create.all.get (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:27:26)
    at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:20:44)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:128:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)

**Comment by eddiemonge** [comment]
check your permissions on `/Users/zan/.config/configstore`

**Comment by ain** [comment]
I've reproduced this as well. NVM is functional, all other tools work as expected, but not `yo`:

```
$ yo --help
/Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/glob/sync.js:321
        throw er
        ^

Error: EACCES: permission denied, scandir '/usr/local/lib/node_modules'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at GlobSync._readdir (/Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/glob/sync.js:275:41)
    at GlobSync._processReaddir (/Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/glob/sync.js:135:22)
    at GlobSync._process (/Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/glob/sync.js:130:10)
    at new GlobSync (/Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/glob/sync.js:46:10)
    at Function.globSync [as sync] (/Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/glob/sync.js:24:10)
    at /Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/globby/index.js:55:35
    at Array.reduce (native)
    at Function.module.exports.sync (/Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/globby/index.js:54:19)

```

**Comment by eddiemonge** [comment]
Does `~/.config/configstore/insight-yo.json` exist?

**Comment by ain** [comment]
It does:

```
$ ls -la ~/.config/configstore/insight-yo.json
-rw-------  1 ain  staff  48 May 17 17:45 /Users/ain/.config/configstore/insight-yo.json
```

Setting it to `0777` did not resolve either.

**Comment by SBoudrias** [comment]
@ain are you sure it had 777 permissions? `chmod` might've failed.

**Comment by ain** [comment]
Yes, it had, but check these 3 consequent commands:

```
Ains-MBP:~ ain$ ls -la ~/.config/configstore/insight-yo.json
-rwxrwxrwx  1 ain  staff  48 May 18 10:44 /Users/ain/.config/configstore/insight-yo.json
Ains-MBP:~ ain$ yo pioneerscss
/Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/glob/sync.js:321
        throw er
        ^

Error: EACCES: permission denied, scandir '/usr/local/lib/node_modules'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at GlobSync._readdir (/Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/glob/sync.js:275:41)
    at GlobSync._processReaddir (/Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/glob/sync.js:135:22)
    at GlobSync._process (/Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/glob/sync.js:130:10)
    at new GlobSync (/Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/glob/sync.js:46:10)
    at Function.globSync [as sync] (/Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/glob/sync.js:24:10)
    at /Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/globby/index.js:55:35
    at Array.reduce (native)
    at Function.module.exports.sync (/Users/ain/.nvm/versions/node/v6.10.3/lib/node_modules/yo/node_modules/globby/index.js:54:19)
Ains-MBP:~ ain$ ls -la ~/.config/configstore/insight-yo.json
-rw-------  1 ain  staff  48 May 18 10:45 /Users/ain/.config/configstore/insight-yo.json
```

**Comment by ain** [comment]
The problem I'm seeing is that it fails at `/usr/local/lib/node_modules` which is invalid location for it to work in:

```
$ npm config get prefix
/Users/ain/.nvm/versions/node/v6.10.3
```

**Comment by ain** [comment]
`sudo chown -R $(whoami) /usr/local` did the trick this time despite the NVM and its paths.

Thanks for the support.
