### ISSUE TITLE
yo installation problem

### ISSUE THREAD

**Issue by arushijain45** [yeoman/yo#384]
Hello people. I have installed yaemon in my system ubuntu 12.0.4 using following command:
sudo npm install -g yo
But when I try to check it using following command yo --version, it shows me this error. I have struggled it everywhere but could not get working solution.

module.js:339
    throw err;
    ^

Error: Cannot find module 'duplexify'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/yo/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/got/index.js:10:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

Please help.

**Comment by SBoudrias** [comment]
Installation is handled by `npm`. That's an error on their side, we can't help you much.

Have you tried with the latest npm version? Otherwise, `rm -rf node_modules` and try again.
