### ISSUE TITLE
Does not run in Docker

### ISSUE THREAD

**Issue by mlb-** [yeoman/yo#452]
With a Dockerfile:
```
FROM node
RUN npm install -g yo
RUN yo
```

I get (snipped output):
```
  `-- yosay@1.1.1
    +-- pad-component@0.0.1
    +-- taketalk@1.0.0
    | +-- get-stdin@4.0.1
    | `-- minimist@1.2.0
    `-- wrap-ansi@2.0.0

npm info ok
 ---> 492e3cee1920
Removing intermediate container daac0407ec73
Step 3 : RUN yo
 ---> Running in fbe1ebf3a467
/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.create.all.get (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:172:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
The command '/bin/sh -c yo' returned a non-zero code: 1
```

And debug information:
```
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM node
 ---> 72d4ec634f1f
Step 2 : RUN npm install -g yo
 ---> Using cache
 ---> 492e3cee1920
Step 3 : RUN yo --version && echo $PATH $NODE_PATH && node -e 'console.log(process.platform, process.versions)'
 ---> Running in dfd058d78120
1.8.4
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
linux { http_parser: '2.7.0',
  node: '6.2.1',
  v8: '5.0.71.52',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2h' }
 ---> 9d0397c0dcab
Removing intermediate container dfd058d78120
Successfully built 9d0397c0dcab
```

**Comment by SBoudrias** [comment]
Please google and search in our issue tracker.

These kind of issues have been brought up quite a lot and are not specific to Yeoman.

**Comment by mlb-** [comment]
I'm quite new to Node and Yeoman. Could you spare the time to help orient me in the right direction to start my research? The only other issue I saw in your tracker was from two years ago, and I didn't feel reviving such an old issue would've been the right course of action.

**Comment by mlb-** [comment]
So after examining the stacktrace, it's happily not Yeoman, Insight, *or* configstore! 😄 

So I cloned this repo and did a binary search to identify what in lib/cli.js appears to be the issue. The inclusion of a single line introduces a side effect that changes how the code following it operates: https://github.com/yeoman/yo/blob/master/lib/cli.js#L162

**Comment by mlb-** [comment]
Ah ha! This is an issue specific to Yeoman: https://github.com/yeoman/yo/commit/dc4e0d907e2c27b2215f4aa5761524a44e2065d6

**Comment by mlb-** [comment]
I updated the issue so others can find this and don't need to dig as far as I needed to. Hope this is okay.
