### ISSUE TITLE
postinstall script error node v6.2.2 npm 3.10.2

### ISSUE THREAD

**Issue by christopherreay** [yeoman/yo#458]
28232 verbose stack Error: spawn-sync@1.0.15 postinstall: `node postinstall`
28232 verbose stack Exit status 1
28232 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/v6.2.2/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
28232 verbose stack     at emitTwo (events.js:106:13)
28232 verbose stack     at EventEmitter.emit (events.js:191:7)
28232 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/v6.2.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)
28232 verbose stack     at emitTwo (events.js:106:13)
28232 verbose stack     at ChildProcess.emit (events.js:191:7)
28232 verbose stack     at maybeClose (internal/child_process.js:852:16)
28232 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
28233 verbose pkgid spawn-sync@1.0.15
28234 verbose cwd /home/administrator/thisEqualsThat
28235 error Linux 3.2.0-24-virtual
28236 error argv "/root/.nvm/v6.2.2/bin/node" "/root/.nvm/v6.2.2/bin/npm" "install" "-g" "yo"
28237 error node v6.2.2
28238 error npm  v3.10.2
28239 error code ELIFECYCLE
28240 error spawn-sync@1.0.15 postinstall: `node postinstall`
28240 error Exit status 1
28241 error Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
28241 error Make sure you have the latest version of node.js and npm installed.
28241 error If you do, this is most likely a problem with the spawn-sync package,
28241 error not with npm itself.
28241 error Tell the author that this fails on your system:
28241 error     node postinstall
28241 error You can get information on how to open an issue for this project with:
28241 error     npm bugs spawn-sync
28241 error Or if that isn't available, you can get their info via:
28241 error     npm owner ls spawn-sync
28241 error There is likely additional logging output above.
28242 verbose exit [ 1, true ]
root@thisEquals:/home/administrator/thisEqualsThat# node --version
v6.2.2
root@thisEquals:/home/administrator/thisEqualsThat# npm --version
3.10.2
root@thisEquals:/home/administrator/thisEqualsThat#

**Comment by christopherreay** [comment]
OK, its an issue with spawn-sync

This fixed it:

npm install -g yo --unsafe-perm
(scripts are run with lower permissions by default)

**Comment by christopherreay** [comment]
In general, dont use root when working with this stuff. I never got it to work. Something to do with user id 501 being used in parts of the process for security.

Not logged in as root worked perfectly
