### ISSUE TITLE
Yeoman Hubot Installation failed and yo doctor gives error

### ISSUE THREAD

**Issue by mullaiarasu** [yeoman/yo#471]
Hi, 

I was using yeoman to install the Hubot and I have received below errors
Machine is redhat linux and kernel version 3.10.0-327.el7.x86_64

```
[root@ip-10-124-64-90 ~]# npm install -g yo
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/bin/yo -> /lib/node_modules/yo/lib/cli.js
/bin/yo-complete -> /lib/node_modules/yo/lib/completion/index.js

> spawn-sync@1.0.15 postinstall /lib/node_modules/yo/node_modules/spawn-sync
> node postinstall

Installing native dependencies (this may take up to a minute)

> yo@1.8.5 postinstall /lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ No .bowerrc file in home directory
✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✖ Node.js version
```

So When I tried to update the Node.Js I received  it is already the latest package
```
[root@ip-10-124-64-90 ~]#
[root@ip-10-124-64-90 ~]# node -v
v0.10.46
[root@ip-10-124-64-90 ~]# npm -v
3.10.6
[root@ip-10-124-64-90 ~]#
[root@ip-10-124-64-90 ~]#
[root@ip-10-124-64-90 ~]#
[root@ip-10-124-64-90 ~]# yum install nodejs
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Package nodejs-0.10.46-1nodesource.el7.centos.x86_64 already installed and latest version
Nothing to do
[root@ip-10-124-64-90 ~]#
[root@ip-10-124-64-90 ~]#
```

When I wanted to check it with the yo doctor I faced below issue

```
[root@ip-10-124-64-90 ~]# yo doctor
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /usr/lib/node_modules/yo/node_modules/spawn-sync/error.log for more details

Error: EACCES, permission denied '/root/.config/configstore/insight-yo.json.2705457532'
You don't have access to this file
```
These are the error messages in the spawn-sync error.log

```
[root@ip-10-124-64-90 ~]# cat /usr/lib/node_modules/yo/node_modules/spawn-sync/error.log
Error: EACCES, permission denied '/usr/lib/node_modules/yo/node_modules/spawn-sync/package.json'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.writeFileSync (fs.js:978:15)
    at Object.<anonymous> (/usr/lib/node_modules/yo/node_modules/spawn-sync/postinstall.js:28:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3[root@ip-10-124-64-90 ~]#
```

When I check the permission for the package.json file it was already there.

```
[root@ip-10-124-64-90 ~]# ls -lthr /usr/lib/node_modules/yo/node_modules/spawn-sync/package.json
-rw-r--r--. 1 root root 2.4K Sep  7 19:29 /usr/lib/node_modules/yo/node_modules/spawn-sync/package.json
[root@ip-10-124-64-90 ~]#
```

Kindly help me to debug this issue.

So incase you were wondering to install the v12 verion of the Node.js it is not supported for RHEL kernel 

```
[root@ip-10-124-64-90 ~]# curl -sL https://rpm.nodesource.com/setup_0.12 | bash -

## Installing the NodeSource Node.js v0.12 repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_0.12/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Your distribution, identified as "redhat-release-server-7.2-9.el7.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

[root@ip-10-124-64-90 ~]#

```

**Comment by SBoudrias** [comment]
Hi, can you start by reading the error message before asking for help?

I think the error message give you plenty of information to start searching for fixes.
