### ISSUE TITLE
Updates for Tutorial(codelab)

### ISSUE THREAD

**Issue by ShawnTe** [yeoman/yo#476]
Thanks for the easy-to-follow tutorial! 

A few minor discrepancies between the tutorial and actual response for update (totally not urgent, these did not prevent any functionality -- just wanted to help keep things current):

On http://yeoman.io/codelab/scaffold-app.html 
the following options in the CLI are missing from the tutorial page:

"Which Continuous Integration platform do you want? (Press <space> to select)
❯◯ Travis
 ◯ CircleCi
 ◯ Jenkins (with Dockerfile)
 ◯ Wercker"

Then, asked for (in CLI):
 "Would you like a router? (Use arrow keys)
❯ React router
  None"

And on page: http://yeoman.io/codelab/local-storage.html
Tis written:
"We can confirm whether our data is being persisted to local storage by checking the Resources panel in Chrome DevTools and selecting Local Storage from the lefthand side:

In Chrome Dev Tools, this now is in (in mine anyways??):
Application -- Storage -- Local Storage"

Cheers!

**Comment by SBoudrias** [comment]
@zckrs ^^

**Comment by zckrs** [comment]
Thank you @shawnte.

I will try to fix today.

**Comment by addyosmani** [comment]
Thanks for making the time, @zckrs :)

**Comment by EricKramp** [comment]
Hi, 

This may warrant a new bug, but I thought I'd ask the thread. I was just working my way through that tutorial and it went fine until the build step (Step 8), any my build failed. I have confirmed that I'm using the latest version of node/npm, and yo version 1.8.5, basically a fresh install of everything.

Here's my npm log, and I'm happy to add any additional info.

[npm-debug.txt](https://github.com/yeoman/yo/files/764746/npm-debug.txt)

**Comment by dandymi** [comment]
Hi,
I'm using yo version 1.8.5 and following strictly the tutorial, I always jump to this bug:

daniele@socrate /opt/projects/mytodo $ yo
? ==========================================================================
We're constantly looking for ways to make yo better! 
May we anonymously report usage statistics to improve the tool over time? 
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== Yes
? 'Allo daniele! What would you like to do? Fountain Webapp

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo fountain-webapp


     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

/home/daniele/.npm-packages/lib/node_modules/generator-fountain-webapp/node_modules/fountain-generator/lib/Base.js:21
    const {framework, modules, js} = this.options;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/daniele/.npm-packages/lib/node_modules/generator-fountain-webapp/node_modules/fountain-generator/index.js:2:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by SBoudrias** [comment]
@dandymi You need to use Node version 4 or higher.

**Comment by dandymi** [comment]
daniele@socrate ~ $ node --version
v4.2.6

**Comment by zckrs** [comment]
You use a old node version.

(Last LTS node 4)[https://nodejs.org/en/blog/release/v4.7.2/]

**Comment by cblair32** [comment]
Catching the same error as @dandymi 
Updated node to latest and went back all the way to node 4.

**Comment by smcgarrigle** [comment]
@cblair32 @dandymi - I had the exact same problem and I ended up uninstalling Node, NPM and NVM because i had older versions installed in odd locations

This stackoverflow was helpful (read all the answers) http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

I reinstalled node/npm/nvm with brew and the tutorial works now

**Comment by Jogesh0x1** [comment]
Was getting same error as @dandymi 

uninstalled node and installed latest version, from repair install and remove/clean option on windows, first did remove and then install.

Able to progress with steps now

**Comment by VictorHugoDotVn** [comment]
Hi all,
I have an error:

[12:30:46] Time: 9814ms
       Asset     Size  Chunks  Chunk Names
    index.js  1.52 MB       0  main
index.js.map  1.69 MB       0  main

ERROR in ./src/app/components/TodoTextInput.js

/Users/trinhbaloi/mytodo/src/app/components/TodoTextInput.js
  40:13  error  Unnecessarily quoted property 'edit' found  quote-props

✖ 1 problem (1 error, 0 warnings)

 @ ./src/app/components/Header.js 221:21-47
 @ ./src/app/containers/App.js
 @ ./src/index.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client ./src/index
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  568 kB       0  
[12:30:46] Finished 'webpack:watch' after 9.84 s
[12:30:46] Starting 'watch'...
[12:30:46] Finished 'watch' after 56 ms
[12:30:46] Starting 'browsersync'...
[12:30:46] Finished 'browsersync' after 68 ms
[12:30:46] Finished 'serve' after 9.96 s

Can you please advise and help, pls. Thanks.

**Comment by olliebaum** [comment]
I'm doing the tutorial now and have noticed the discrepancies @ShawnTe mentions are still there. I'm assuming the options I'm meant to select are none and none? It would be nice if that could be updated because I'm a complete Yeoman newbie and so got kinda foxed by this.
