### ISSUE TITLE
yo react-flux what's wrong with my command

### ISSUE THREAD

**Issue by huutinh2712** [yeoman/yo#538]
huutinh@huutinh-virtual-machine:~/Desktop/huyenthanh$ yo react-flux/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/home/huutinh/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Configstore.get (/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:34:26)
    at Configstore (/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:38:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:43:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)

**Comment by SBoudrias** [comment]
That's a permission issue on your OS. You can find a lot of help on this subject if you google it. https://en.wikipedia.org/wiki/Chmod

I'll close this issue as it is not actionnable by us.
