### ISSUE TITLE
yo angular-2-crud:server     TypeError: Generator.extend is not a function

### ISSUE THREAD

**Issue by xlinx69** [yeoman/yo#543]
Error when running :
yo angular-2-crud:server      = >     TypeError: Generator.extend is not a function

## Type of issue

bug

## My environment

* *OS version/details:  Windows 10 64-bit`
* *Node version: 6.11.1
* *npm version: 3.10.10
* *Version of yo : 2.0.0 

## Expected behavior

running the server correctly 

## Current behavior

error 

## Steps to reproduce the behavior

repetable

## Command line output

yo angular-2-crud:server
C:\Users\cdena\AppData\Roaming\npm\node_modules\generator-angular-2-crud\generators\server\index.js:9
module.exports = Generator.extend({
                           ^

TypeError: Generator.extend is not a function
    at Object.<anonymous> (C:\Users\cdena\AppData\Roaming\npm\node_modules\generator-angular-2-crud\generators\server\index.js:9:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as angular-2-crud:server] (C:\Users\cdena\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:38:27)
    at Store.get (C:\Users\cdena\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:61:39)

**Comment by SBoudrias** [comment]
Please open an issue on `generator-angular-2-crud` repository.

With over 5000 generators in our ecosystem, the Yeoman core team cannot support all of them.

In this case, it looks like this generator use the latest `yeoman-generator` version, but that they didn't update to use our new API.
