### ISSUE TITLE
Step 8 Build Error

### ISSUE THREAD

**Issue by rbrownpa** [yeoman/yo#565]
## Type of issue

----

## My environment

* *OS version/details*: `eg. Windows 10 64-bit`
* *Node version:* `x.x.x` (run `node --version` in your terminal)
* *npm version:* `x.x.x` (run `npm --version` in your terminal)
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Command line output

```
Paste your error output over here
```
mytodo/gulp_tasks/browsersync.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
```
[2018-01-31T23_08_56_574Z-debug.log](https://github.com/yeoman/yo/files/1683676/2018-01-31T23_08_56_574Z-debug.log)

**Comment by SBoudrias** [comment]
That's cause by the specific generator you're using to generate your project. Yeoman itself (the tool) doesn't rely on webpack.

**Comment by rbrownpa** [comment]
FYI, I am using the demo in yeoman. I am not sure if you want people to be able to learn how to use yeoman with a defective demo, but your answer is not helpful. On Feb 5, 2018 11:00 AM, Simon Boudrias <notifications@github.com> wrote:That's cause by the specific generator you're using to generate your project. Yeoman itself (the tool) doesn't rely on webpack.

**Comment by SBoudrias** [comment]
I'm sorry, but your ticket wasn't very descriptive. You must understand we receive a lot of bogus bug reports, so it's hard to filter through the noise when context is missing. I appreciate you spending time opening this issue; but also be mindful of the position of open source project maintainers are.

cc @zckrs do you think that's an issue with generator-fountainjs?

**Comment by willmendesneto** [comment]
@rbrownpa could you add more information about this issue, please? 

- nodejs version;
- npm Version;
- yeoman Version;
- yeoman generator version;
