### ISSUE TITLE
can't start any generator

### ISSUE THREAD

**Issue by Leolik** [yeoman/yo#576]
## Type of issue

when I try start any yo generator - I get error

----

## My environment

* *OS version/details*: MacOS 10.13.4 (17E202)
* *Node version:* v10.1.0
* *npm version:* 5.6.0
* *Version of yo :* 2.0.2

## Expected behavior

run installed configurator

## Current behavior

get error

## Steps to reproduce the behavior
```
npm install --global yo
npm install --global generator-webapp
yo webapp
```

## Command line output

```
/usr/local/lib/node_modules/yo/node_modules/fast-glob/out/providers/reader-sync.js:45
            throw err;
            ^

Error: EACCES: permission denied, scandir '/usr/sbin/authserver'
    at Object.fs.readdirSync (fs.js:875:3)
    at exports.readdir (/usr/local/lib/node_modules/yo/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/usr/local/lib/node_modules/yo/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/usr/local/lib/node_modules/yo/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at Readable.DirectoryReader.stream._read (/usr/local/lib/node_modules/yo/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (_stream_readable.js:455:10)
    at readdirSync (/usr/local/lib/node_modules/yo/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/usr/local/lib/node_modules/yo/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/usr/local/lib/node_modules/yo/node_modules/fast-glob/out/providers/reader-sync.js:61:24)
    at ReaderSync.api (/usr/local/lib/node_modules/yo/node_modules/fast-glob/out/providers/reader-sync.js:53:25)
Emitted 'error' event at:
    at DirectoryReader.emit (/usr/local/lib/node_modules/yo/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:365:14)
    at call.safe (/usr/local/lib/node_modules/yo/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:81:14)
    at onceWrapper (/usr/local/lib/node_modules/yo/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:45:17)
    at onceWrapper (/usr/local/lib/node_modules/yo/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:45:17)
    at exports.readdir (/usr/local/lib/node_modules/yo/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:22:5)
    at Object.safeCall [as safe] (/usr/local/lib/node_modules/yo/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    [... lines matching original stack trace ...]
    at readdirSync (/usr/local/lib/node_modules/yo/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
```

**Comment by SBoudrias** [comment]
Related to https://github.com/yeoman/environment/issues/97

**Comment by AnthonyNahas** [comment]
@Leolik Im facing the same issue after I updated yo to the latest version!
Rollback did not help!

**Comment by SBoudrias** [comment]
The fix is released. Try `npm update -g yo` or uninstall/reinstall.

**Comment by AnthonyNahas** [comment]
@Leolik npm update did not work!
How ever `npm un -g yo` then `npm i -g yo` did it 👍 
thank you

**Comment by Leolik** [comment]
@SBoudrias @AnthonyNahas thanks! after update yo work fine!
