### ISSUE TITLE
Must provide at least one argument, the generator namespace to invoke.

### ISSUE THREAD

**Issue by johnzhu12** [yeoman/yo#578]
## error
`Error: Must provide at least one argument, the generator namespace to invoke.
    at Environment.run (/Users/johnzhu/Desktop/work_Space/yo-noive/generator-rocky/node_modules/yeoman-environment/lib/environment.js:369:23)
    at Environment.run (/Users/johnzhu/.nvm/versions/node/v9.4.0/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:451:22)
    at module.exports (/Users/johnzhu/.nvm/versions/node/v9.4.0/lib/node_modules/yo/lib/routes/run.js:19:11)
    at Router.navigate (/Users/johnzhu/.nvm/versions/node/v9.4.0/lib/node_modules/yo/lib/router.js:36:32)
    at inquirer.prompt.then.answer (/Users/johnzhu/.nvm/versions/node/v9.4.0/lib/node_modules/yo/lib/routes/home.js:73:13)
    at <anonymous>
`
![1527231027872](https://user-images.githubusercontent.com/11485619/40530384-26a8e7d8-602b-11e8-964e-fdf2e6469a03.jpg)

----

## My environment

* *OS version/details*: osx 10.13.1
* *Node version:* `v9.4.0` 
* *npm version:* `5.6.0`
* *Version of yo :* `2.0.2`

**Comment by johnzhu12** [comment]
```javascript
   var name = args.shift();
  if (!name) {
    return this.error(new Error('Must provide at least one argument, the generator namespace to invoke.'));
  }
```
 I found this line in the source. what does the name mean."yo+name"=>"yo+rocky",haven't I provide the rocky name

**Comment by johnzhu12** [comment]
```javascript
  console.log("I'm args", args) // I'm args []
  var name = args.shift();
``` 
 the log shows as above

**Comment by johnzhu12** [comment]
all right, update to 2.0.0,fix it!
