### ISSUE TITLE
npm install fails, Cannot find module '.'

### ISSUE THREAD

**Issue by vScourge** [yeoman/yo#596]
## Type of issue

bug

----

## My environment

Windows 10 64-bit
Node version: 0.12.2
npm version: 2.7.4
Version of yo: not installed

## Expected behavior

Getting yo to install via npm.

## Current behavior

npm fails to install yo on my system.  I'm trying to get it in order to generate some VS Code extension templates.  I've tried both of these commands from a command prompt:

npm install -g yo generator-code
npm install yo

The install process works for a bit then fails with this:

```
> spawn-sync@1.0.15 postinstall C:\WINDOWS\system32\node_modules\yo\node_modules\tabtab\node_modules\inquirer\node_modules\external-editor\node_module
s\spawn-sync
> node postinstall

-
> yo@2.0.4 postinstall C:\WINDOWS\system32\node_modules\yo
> yodoctor

module.js:338
    throw err;
          ^
Error: Cannot find module '.'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Windows\System32\node_modules\yo\node_modules\yeoman-doctor\lib\cli.js:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "yo"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! yo@2.0.4 postinstall: `yodoctor`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yo@2.0.4 postinstall script 'yodoctor'.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

C:\WINDOWS\system32>
```

## Steps to reproduce the behavior

I was just using these commands:
npm install -g yo generator-code
npm install yo

## Command line output

See above.

**Comment by vScourge** [comment]
Thanks.  After cleaning out the older release the new one is working fine.
