### ISSUE TITLE
yo doctor command is throwing error

### ISSUE THREAD

**Issue by ssinhaprgx** [yeoman/yo#601]
root@ubuntu-4gb-nbg1-1 ~ # npm -v
5.6.0
root@ubuntu-4gb-nbg1-1 ~ # node -v
v8.10.0
root@ubuntu-4gb-nbg1-1 ~ # yo --version (-v is throwing same error)
2.0.5

root@ubuntu-4gb-nbg1-1 ~ # yo doctor
/usr/local/lib/node_modules/yo/node_modules/write-file-atomic/index.js:197
    throw err
    ^

Error: EACCES: permission denied, open '/root/.config/insight-nodejs/insight-yo.json.160537966'
    at Object.fs.openSync (fs.js:646:18)
    at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/yo/node_modules/write-file-atomic/index.js:180:17)
    at Conf.set store [as store] (/usr/local/lib/node_modules/yo/node_modules/conf/index.js:142:19)
    at Conf.set (/usr/local/lib/node_modules/yo/node_modules/conf/index.js:64:14)
    at Insight.set optOut [as optOut] (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:56:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:198:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

**Comment by bboulahdid** [comment]
Did you try running the command with `sudo` ?

**Comment by JoshuaKGoldberg** [comment]
Yup, looks like a permissions issue from 6+ years ago. I'll go ahead and close this out as aged way. Cheers! 🎩
