### ISSUE TITLE
Invalid tag name "foreachasync@^3.0.0": Tags may not have any characters that encodeURIComponent encodes.

### ISSUE THREAD

**Issue by VickyKoblinski** [yeoman/yo#602]
## Type of issue

Bug

----

## My environment

* *OS version/details*: `Windows 10 64-bit`
* *Node version:* `8.9.4` 
* *npm version:* `6.4.1` 
* *Version of yo :* `N/A`

## Expected behavior

Install yo successfully

## Current behavior

Does not install yo

## Steps to reproduce the behavior

1. `npm install -g yo`

## Notes

I tried updating npm (from 5.x to 6.4.1) and that didn't solve the problem.

I tried doing a `yarn global add yo` and that DID install yo successfully.

yarn version: `1.9.4`

## Command line output

Short log
```
C:\Users\me\projects>npm install -g yo
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "foreachasync@^3.0.0": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2018-10-15T20_27_49_647Z-debug.log
```

Long log
```
1075 silly resolveWithNewModule forEachAsync@3.0.0 checking installable status
1076 verbose stack Error: Invalid tag name "foreachasync@^3.0.0": Tags may not have any characters that encodeURIComponent encodes.
1076 verbose stack     at invalidTagName (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:87:15)
1076 verbose stack     at fromRegistry (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:290:13)
1076 verbose stack     at Function.resolve (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:77:12)
1076 verbose stack     at doesChildVersionMatch (C:\Users\me\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:75:25)
1076 verbose stack     at isDep (C:\Users\me\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:147:27)
1076 verbose stack     at addRequiredDep (C:\Users\me\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:159:13)
1076 verbose stack     at addBundled (C:\Users\me\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:674:7)
1076 verbose stack     at addBundled (C:\Users\me\AppData\Roaming\npm\node_modules\npm\lib\fetch-package-metadata.js:93:78)
1076 verbose stack     at isInstallable (C:\Users\me\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:652:5)
1076 verbose stack     at checkPlatform (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\npm-install-checks\index.js:53:10)
1076 verbose stack     at thenWarnEngineIssues (C:\Users\me\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:52:5)
1076 verbose stack     at a (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\iferr\iferr.js:3:64)
1076 verbose stack     at checkEngine (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\npm-install-checks\index.js:10:20)
1076 verbose stack     at module.exports.isInstallable (C:\Users\me\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:49:3)
1076 verbose stack     at resolveWithNewModule (C:\Users\me\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:650:10)
1076 verbose stack     at C:\Users\me\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:573:7
1077 verbose cwd C:\Users\me\projects
1078 verbose Windows_NT 10.0.15063
1079 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
1080 verbose node v8.9.4
1081 verbose npm  v6.4.1
1082 error code EINVALIDTAGNAME
1083 error Invalid tag name "foreachasync@^3.0.0": Tags may not have any characters that encodeURIComponent encodes.
1084 verbose exit [ 1, true ]
```

**Comment by thematho** [comment]
@VickyKoblinski Did you found any Workaround  ?
