### ISSUE TITLE
yo teams thrown an error - typescript is missing

### ISSUE THREAD

**Issue by Nicosoft** [yeoman/yo#604]
Hi there,

As you can see below ```$ yo teams``` throws an error. It seems typescript module is missing. But I did install it:

```
sudo npm install typescript --global
Password:
/usr/local/bin/tsc -> /usr/local/lib/node_modules/typescript/bin/tsc
/usr/local/bin/tsserver -> /usr/local/lib/node_modules/typescript/bin/tsserver
+ typescript@3.1.6
updated 1 package in 4.494s
Nicolass-MacBook-Pro:~ nicoj$ yo teams
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/nicoj/node_modules/generator-teams/generators/app/index.js:1:2200)
    at i (/Users/nicoj/node_modules/generator-teams/generators/app/index.js:1:186)
    at Object.<anonymous> (/Users/nicoj/node_modules/generator-teams/generators/app/index.js:1:1219)
    at i (/Users/nicoj/node_modules/generator-teams/generators/app/index.js:1:186)
    at Object.<anonymous> (/Users/nicoj/node_modules/generator-teams/generators/app/index.js:1:2785)
    at i (/Users/nicoj/node_modules/generator-teams/generators/app/index.js:1:186)
```

###Additional Info###
```
$ yo doctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
✔ yo version

Everything looks all right!

```

Appreciate any help!
Thanks

**Comment by Nicosoft** [comment]
I fixed this issue by installing 'typescript' locally instead of global:
`sudo npm install typescript` 

Hope this help someone else.

**Comment by SBoudrias** [comment]
Please report bugs running a generator on the specific generator repository.

The Yeoman team works on the core system and unfortunately cannot maintain the ~5000 publicly available generators. Thanks for your understanding!
