### ISSUE TITLE
Installing yo get throw new ERR_OUT_OF_RANGE

### ISSUE THREAD

**Issue by sangdth** [yeoman/yo#605]
## Type of issue

Bug (error) when installing new yo with `npm install -g yo`

----

## My environment

* *OS version/details*: `MacOS Mojave 10.14`
* *Node version:* `10.13.0` 
* *npm version:* `6.4.1` 
* *Version of yo :* `0`

## Expected behavior
Install should be smooth and can use `yo` after finish.

## Current behavior
Can not use `yo`

## Steps to reproduce the behavior
Run `npm install -g yo`

## Command line output

```
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
util.js:371
    throw new ERR_OUT_OF_RANGE('err', 'a negative integer', err);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 536870174
    at Object.getSystemErrorName (util.js:371:11)
    at exceptionWithHostPort (internal/errors.js:333:21)
    at internalConnect (net.js:884:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1031:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yo@2.0.5 postinstall: `yodoctor`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yo@2.0.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sangdth/.npm/_logs/2018-11-03T19_04_20_826Z-debug.log
```

**Comment by SBoudrias** [comment]
This looks like a Node error; which version are you using? Did you search Node.js bug tracker?

**Comment by itslooklike** [comment]
fix this problem after disable LuLu (proxy app) https://github.com/objective-see/LuLu/issues/150

**Comment by mshima** [comment]
Great.
This isn’t a yo bug.
Closing.
