### ISSUE TITLE
TypeError: Cannot read property 'proxy' of undefined

### ISSUE THREAD

**Issue by behrangsa** [yeoman/yo#620]
## Bug

When running `npx -p yo -p @custom/generator-custom-app -c 'yo @custom/custom-app`, an error `TypeError: Cannot read property 'proxy' of undefined` occurs.

## My environment

* *OS version/details*: `macOS 10.14.5`
* *Node version:* `v12.4.0` 
* *npm version:* `6.9.0` 
* *Version of yo :* `2.0.6` 

## Expected behavior

Yeoman not to encounter `TypeError: Cannot read property 'proxy' of undefined`

## Current behavior

Yeoman encounters `TypeError: Cannot read property 'proxy' of undefined`:

```
TypeError: Cannot read property 'proxy' of undefined
    at new OuterHttpAgent (/Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/global-tunnel-ng/lib/agents.js:17:28)
    at new ClientRequest (_http_client.js:116:13)
    at TunnelingAgent.request (http.js:44:10)
    at TunnelingAgent.createSocket (/Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:126:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:207:41)
    at TunnelingAgent.addRequest (/Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:84:8)
    at new ClientRequest (_http_client.js:276:16)
    at Object.request (https.js:309:10)
    at Object.request (/Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/global-tunnel-ng/index.js:336:40)
    at get (/Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/latest-version/node_modules/got/index.js:33:18)
(node:29391) UnhandledPromiseRejectionWarning: Error: callback() can only be called once.
    at onetime (/Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/each-async/node_modules/onetime/index.js:15:11)
    at /Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/yeoman-doctor/lib/index.js:23:7
    at /Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/yeoman-doctor/lib/rules/yo-version.js:21:23
(node:29391) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:29391) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Steps to reproduce the behavior

Not easy to replicate (using private NPM repository with a custom generator). But the error seems to happen in this line:

```
mixinProxying(this, opts.proxy);
```

of `.npm/_npx/29063/lib/node_modules/yo/node_modules/global-tunnel-ng/lib/agents.js`:

```
/* jshint node:true */
'use strict';

var util = require('util');
var http = require('http');
var HttpAgent = http.Agent;
var https = require('https');
var HttpsAgent = https.Agent;

var pick = require('lodash/pick');

/**
 * Proxy some traffic over HTTP.
 */
function OuterHttpAgent(opts) {
  HttpAgent.call(this, opts);
  mixinProxying(this, opts.proxy);
}
util.inherits(OuterHttpAgent, HttpAgent);
exports.OuterHttpAgent = OuterHttpAgent;

/**
 * Proxy some traffic over HTTPS.
 */
function OuterHttpsAgent(opts) {
  HttpsAgent.call(this, opts);
  mixinProxying(this, opts.proxy);
}
util.inherits(OuterHttpsAgent, HttpsAgent);
exports.OuterHttpsAgent = OuterHttpsAgent;

/**
 * Override createConnection and addRequest methods on the supplied agent.
 * http.Agent and https.Agent will set up createConnection in the constructor.
 */
function mixinProxying(agent, proxyOpts) {
  agent.proxy = proxyOpts;

  var orig = pick(agent, 'createConnection', 'addRequest');

  // Make the tcp or tls connection go to the proxy, ignoring the
  // destination host:port arguments.
  agent.createConnection = function(port, host, options) {
    return orig.createConnection.call(this, this.proxy.port, this.proxy.host, options);
  };

  agent.addRequest = function(req, options) {
    req.path =
      this.proxy.innerProtocol + '//' + options.host + ':' + options.port + req.path;
    return orig.addRequest.call(this, req, options);
  };
}
```

**Comment by magickaichen** [comment]
Have the same issues here, please fix this asap.

**Comment by jose-amey** [comment]
Hi 
I have the same issue in  Centos 7.6.

**Comment by behrangsa** [comment]
Yes, this can be reproduced even just by installing `yo`:

```
$ npm install -g yo@latest
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
/Users/MaUserName/.node_modules/bin/yo -> /Users/MaUserName/.node_modules/lib/node_modules/yo/lib/cli.js
/Users/MaUserName/.node_modules/bin/yo-complete -> /Users/MaUserName/.node_modules/lib/node_modules/yo/lib/completion/index.js

> spawn-sync@1.0.15 postinstall /Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall


> yo@2.0.6 postinstall /Users/MaUserName/.node_modules/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
TypeError: Cannot read property 'proxy' of undefined
    at new OuterHttpAgent (/Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/global-tunnel-ng/lib/agents.js:17:28)
    at new ClientRequest (_http_client.js:116:13)
    at TunnelingAgent.request (http.js:44:10)
    at TunnelingAgent.createSocket (/Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:126:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:207:41)
    at TunnelingAgent.addRequest (/Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:84:8)
    at new ClientRequest (_http_client.js:276:16)
    at Object.request (https.js:309:10)
    at Object.request (/Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/global-tunnel-ng/index.js:336:40)
    at get (/Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/latest-version/node_modules/got/index.js:33:18)
✖ yo version
TypeError: Cannot read property 'proxy' of undefined
    at new OuterHttpAgent (/Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/global-tunnel-ng/lib/agents.js:17:28)
    at new ClientRequest (_http_client.js:116:13)
    at TunnelingAgent.request (http.js:44:10)
    at TunnelingAgent.createSocket (/Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:126:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:207:41)
    at TunnelingAgent.addRequest (/Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:84:8)
    at new ClientRequest (_http_client.js:276:16)
    at Object.request (https.js:309:10)
    at Object.request (/Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/global-tunnel-ng/index.js:336:40)
    at get (/Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/latest-version/node_modules/got/index.js:33:18)
✖ yo version

Your yo version is outdated.

Upgrade to the latest version by running:
npm install -g yo@latest

(node:29401) UnhandledPromiseRejectionWarning: Error: callback() can only be called once.
    at onetime (/Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/each-async/node_modules/onetime/index.js:15:11)
    at /Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/yeoman-doctor/lib/index.js:23:7
    at /Users/MaUserName/.node_modules/lib/node_modules/yo/node_modules/yeoman-doctor/lib/rules/yo-version.js:21:23
(node:29401) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:29401) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Found potential issues on your machine :(
+ yo@2.0.6
added 541 packages from 267 contributors in 76.745s
```

**Comment by behrangsa** [comment]
Node v8.16.0 (npm v6.4.1) throws another error:

```
$ npm install -g yo @nab/generator-nab-x-miniapp
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
/Users/SomeOne/.nvm/versions/node/v8.16.0/bin/yo-complete -> /Users/SomeOne/.nvm/versions/node/v8.16.0/lib/node_modules/yo/lib/completion/index.js
/Users/SomeOne/.nvm/versions/node/v8.16.0/bin/yo -> /Users/SomeOne/.nvm/versions/node/v8.16.0/lib/node_modules/yo/lib/cli.js

> yo@2.0.6 postinstall /Users/SomeOne/.nvm/versions/node/v8.16.0/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
{ RequestError: unable to get local issuer certificate
    at ClientRequest.req.once.err (/Users/SomeOne/.nvm/versions/node/v8.16.0/lib/node_modules/yo/node_modules/latest-version/node_modules/got/index.js:73:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  message: 'unable to get local issuer certificate',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo' }
✖ yo version
{ RequestError: unable to get local issuer certificate
    at ClientRequest.req.once.err (/Users/SomeOne/.nvm/versions/node/v8.16.0/lib/node_modules/yo/node_modules/latest-version/node_modules/got/index.js:73:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  message: 'unable to get local issuer certificate',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo' }
✖ yo version

Your yo version is outdated.

Upgrade to the latest version by running:
npm install -g yo@latest

(node:52154) UnhandledPromiseRejectionWarning: Error: callback() can only be called once.
    at onetime (/Users/SomeOne/.nvm/versions/node/v8.16.0/lib/node_modules/yo/node_modules/each-async/node_modules/onetime/index.js:15:11)
    at rule.verify.err (/Users/SomeOne/.nvm/versions/node/v8.16.0/lib/node_modules/yo/node_modules/yeoman-doctor/lib/index.js:23:7)
    at binVersionCheck.then (/Users/SomeOne/.nvm/versions/node/v8.16.0/lib/node_modules/yo/node_modules/yeoman-doctor/lib/rules/yo-version.js:21:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:52154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:52154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✔ npm version

Found potential issues on your machine :(
npm WARN eslint-config-react-app@3.0.8 requires a peer of eslint@5.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-flowtype@2.50.3 requires a peer of eslint@>=2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.14.2 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.18.0 requires a peer of eslint@2.x - 6.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsx-a11y@6.2.1 requires a peer of eslint@^3 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.

+ yo@2.0.6
+ @nab/generator-nab-x-miniapp@4.4.1
updated 2 packages in 4.391s
```

Here's my NPM config:

```
$ npm config list
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.4.1 node/v8.16.0 darwin x64"

; userconfig /Users/P781555/.npmrc
cafile = "/usr/local/foo/certificates/foo-internal.cer"
https-proxy = "http://proxy.foo.com.au:10091/"
proxy = "http://proxy.nab.foo.au:10091/"
registry = "https://registry.npmjs.org/"
strict-ssl = false
```

**Comment by behrangsa** [comment]
This seems to be a problem with how `yo` works behind a proxy.

I disabled my computer's proxy:

```
$ printenv | grep -i proxy
✘
$ npm config ls
$ npm config ls
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.9.0 node/v10.16.0 darwin x64"

; userconfig /Users/Hello/.npmrc
registry = "https://registry.npmjs.org/"

; node bin location = /Users/Hello/.nvm/versions/node/v10.16.0/bin/node
; cwd = /Users/Hello/Documents/Projects/github.aus.thenational.com/nab-one
; HOME = /Users/Hello
; "npm config ls -l" to show all defaults.
```

 and connected it to my mobile hotspot and installation succeeded without any errors:

```
$ npm install -g yo
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
/Users/Hello/.nvm/versions/node/v10.16.0/bin/yo -> /Users/Hello/.nvm/versions/node/v10.16.0/lib/node_modules/yo/lib/cli.js
/Users/Hello/.nvm/versions/node/v10.16.0/bin/yo-complete -> /Users/Hello/.nvm/versions/node/v10.16.0/lib/node_modules/yo/lib/completion/index.js

> spawn-sync@1.0.15 postinstall /Users/Hello/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall


> yo@2.0.6 postinstall /Users/Hello/.nvm/versions/node/v10.16.0/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
✔ yo version

Everything looks all right!
+ yo@2.0.6
added 541 packages from 267 contributors in 22.508s
```

**Comment by behrangsa** [comment]
When I go behind the proxy:

```
$ printenv | grep -i proxy
$ printenv | grep -i proxy
NO_PROXY=localhost,127.0.0.*,10.*,.foo.com.au
HTTPS_PROXY=http://proxy.foo.com.au:10091
HTTP_PROXY=http://proxy.foo.com.au:10091

no_proxy=localhost,127.0.0.*,10.*,.foo.com.au
http_proxy=http://proxy.foo.com.au:10091
https_proxy=http://proxy.foo.com.au:10091

$ npm config ls
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.9.0 node/v10.16.0 darwin x64"

; userconfig /Users/sabehrang/.npmrc
https-proxy = "http://proxy.nab.com.au:10091/"
registry = "https://registry.npmjs.org/"
strict-ssl = false

; node bin location = /Users/sabehrang/.nvm/versions/node/v10.16.0/bin/node
; cwd = /Users/sabehrang/Documents/Projects/github.aus.thenational.com/nab-one
; HOME = /Users/sabehrang
; "npm config ls -l" to show all defaults.
```

The error reappears:

```
npm install -g yo
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
/Users/sabehrang/.nvm/versions/node/v10.16.0/bin/yo -> /Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/lib/cli.js
/Users/sabehrang/.nvm/versions/node/v10.16.0/bin/yo-complete -> /Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/lib/completion/index.js

> spawn-sync@1.0.15 postinstall /Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall


> yo@2.0.6 postinstall /Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
TypeError: Cannot read property 'proxy' of undefined
    at new OuterHttpAgent (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/global-tunnel-ng/lib/agents.js:17:28)
    at new ClientRequest (_http_client.js:92:13)
    at TunnelingAgent.request (http.js:42:10)
    at TunnelingAgent.createSocket (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:126:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:207:41)
    at TunnelingAgent.addRequest (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:84:8)
    at new ClientRequest (_http_client.js:249:16)
    at Object.request (https.js:289:10)
    at Object.request (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/global-tunnel-ng/index.js:336:40)
    at get (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/latest-version/node_modules/got/index.js:33:18)
✖ yo version
TypeError: Cannot read property 'proxy' of undefined
    at new OuterHttpAgent (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/global-tunnel-ng/lib/agents.js:17:28)
    at new ClientRequest (_http_client.js:92:13)
    at TunnelingAgent.request (http.js:42:10)
    at TunnelingAgent.createSocket (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:126:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:207:41)
    at TunnelingAgent.addRequest (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:84:8)
    at new ClientRequest (_http_client.js:249:16)
    at Object.request (https.js:289:10)
    at Object.request (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/global-tunnel-ng/index.js:336:40)
    at get (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/latest-version/node_modules/got/index.js:33:18)
✖ yo version

Your yo version is outdated.

Upgrade to the latest version by running:
npm install -g yo@latest

(node:16994) UnhandledPromiseRejectionWarning: Error: callback() can only be called once.
    at onetime (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/each-async/node_modules/onetime/index.js:15:11)
    at rule.verify.err (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/yeoman-doctor/lib/index.js:23:7)
    at binVersionCheck.then (/Users/sabehrang/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/yeoman-doctor/lib/rules/yo-version.js:21:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16994) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:16994) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Found potential issues on your machine :(
+ yo@2.0.6
added 541 packages from 267 contributors in 32.088s
```

**Comment by jose-amey** [comment]
Yes,  Yo is not clear in how it works behind a proxy,  I'll try removing all proxy variables and see what happens.. this still an issue or at least it must be documented how yo works behind proxies

**Comment by jose-amey** [comment]
Still have the issue,  everything points to this : 
/usr/lib/node_modules/yo/node_modules/global-tunnel-ng/lib/agents.js:17

mixinProxying(this, opts.proxy);

**Comment by LitoMore** [comment]
Related to #616

**Comment by jose-amey** [comment]
Thank You .  That solved the issue :)

**Comment by Toolsclub** [comment]
any updates
