### ISSUE TITLE
Error while generating boilerplate for new code snippet

### ISSUE THREAD

**Issue by hydeenoble** [yeoman/yo#639]
## Type of issue

----

## My environment

* *OS version/details*: `MAC OS Catalina`
* *Node version:* `v12.14.1` (run `node --version` in your terminal)
* *npm version:* `6.13.4` (run `npm --version` in your terminal)
* *Version of yo :* `3.1.1` (run `yo --version` in your terminal)

## Expected behavior

After running `yo code` and answering the questions asked, I expect the command to generate a boilerplate for an extension 

## Current behavior

Currently, I get an error after answering the last question. 
## Steps to reproduce the behavior
- run `yo code`
```
? What type of extension do you want to create? New Code Snippets
Folder location that contains Text Mate (.tmSnippet) and Sublime snippets (.sublime-snippet) or press ENTER to start with a new snippet file.
? Folder name for import or none for new: kube-snip
No valid snippets found in kube-snip
? What's the name of your extension? kube-snip
? What's the identifier of your extension? kube-snip
? What's the description of your extension?
Enter the language for which the snippets should appear. The id is an identifier and is single, lower-case name such as 'php', 'javascript'
? Language id: javascript
```
![Uploading Screenshot 2020-02-05 at 12.31.41.png…]()

## Command line output

```
events.js:200
      throw er; // Unhandled 'error' event
      ^

ReferenceError: /Users/hydeenoble/.nvm/versions/node/v12.14.1/lib/node_modules/generator-code/generators/app/templates/ext-snippets/snippets/snippets.json:1
 >> 1| <%- JSON.stringify(snippets, null, '\t') %>

snippets is not defined
    at eval (/Users/hydeenoble/.nvm/versions/node/v12.14.1/lib/node_modules/generator-code/generators/app/templates/ext-snippets/snippets/snippets.json:10:32)
    at snippets (/Users/hydeenoble/.nvm/versions/node/v12.14.1/lib/node_modules/generator-code/node_modules/ejs/lib/ejs.js:682:17)
    at Object.exports.render (/Users/hydeenoble/.nvm/versions/node/v12.14.1/lib/node_modules/generator-code/node_modules/ejs/lib/ejs.js:419:37)
    at render (/Users/hydeenoble/.nvm/versions/node/v12.14.1/lib/node_modules/generator-code/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:14:18)
    at process (/Users/hydeenoble/.nvm/versions/node/v12.14.1/lib/node_modules/generator-code/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:34:16)
    at applyProcessingFunc (/Users/hydeenoble/.nvm/versions/node/v12.14.1/lib/node_modules/generator-code/node_modules/mem-fs-editor/lib/actions/copy.js:14:16)
    at EditionInterface.exports._copySingle (/Users/hydeenoble/.nvm/versions/node/v12.14.1/lib/node_modules/generator-code/node_modules/mem-fs-editor/lib/actions/copy.js:65:16)
    at /Users/hydeenoble/.nvm/versions/node/v12.14.1/lib/node_modules/generator-code/node_modules/mem-fs-editor/lib/actions/copy.js:52:10
    at Array.forEach (<anonymous>)
    at EditionInterface.exports.copy (/Users/hydeenoble/.nvm/versions/node/v12.14.1/lib/node_modules/generator-code/node_modules/mem-fs-editor/lib/actions/copy.js:51:9)
Emitted 'error' event on Generator instance at:
    at Immediate.<anonymous> (/Users/hydeenoble/.nvm/versions/node/v12.14.1/lib/node_modules/generator-code/node_modules/yeoman-generator/lib/index.js:559:18)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:130:23) {
  path: '/Users/hydeenoble/.nvm/versions/node/v12.14.1/lib/node_modules/generator-code/generators/app/templates/ext-snippets/snippets/snippets.json'
}```

**Comment by hydeenoble** [comment]
My bad, I specified a folder name instead of leaving it blank for a new code snippet extension.

`Folder name for import or none for new: kube-snip`

I will close this issue now.
