### ISSUE TITLE
node warns on memory leak?

### ISSUE THREAD

**Issue by hemanth** [yeoman/yo#64]
``` javascript
[?] Search NPM for generators: 
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.EventEmitter.addListener (events.js:168:15)
    at WriteStream.Readable.on (_stream_readable.js:663:33)
    at MuteStream.Stream.pipe (stream.js:65:8)
    at MuteStream.pipe (/Users/hemanth/.nvm/v0.11.2/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/node_modules/mute-stream/mute.js:83:32)
    at Object.Interface.createInterface (/Users/hemanth/.nvm/v0.11.2/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/utils/readline.js:35:6)
    at Object.cli.prompt (/Users/hemanth/.nvm/v0.11.2/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/inquirer.js:48:40)
    at yoyo.prompt (/Users/hemanth/.nvm/v0.11.2/lib/node_modules/yo/node_modules/yeoman-generator/lib/actions/prompt.js:15:19)
    at yoyo._searchNpm (/Users/hemanth/.nvm/v0.11.2/lib/node_modules/yo/bin/yoyo.js:150:8)
    at Object.<anonymous> (/Users/hemanth/.nvm/v0.11.2/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/inquirer.js:77:7)
    at /Users/hemanth/.nvm/v0.11.2/lib/node_modules/yo/node_modules/async/lib/async.js:229:13

```

Installed node using `nvm` and just hit the return key for `[?] Search NPM for generators:`

**Comment by fishenal** [comment]
same problem:
node v 6.9.4
npm v 3.10.7


(node:10768) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
