### ISSUE TITLE
yodoctor fails on install, missing module?

### ISSUE THREAD

**Issue by zacharykane** [yeoman/yo#643]
## Type of issue

A bug, i think...

----

## My environment

* *OS version/details*: `Ubuntu bionic`
* *Node version:* `8`
* *__yarn version:__* `1.22.4`
* *Version of yo :* `2.0.6`

## Expected behavior

It's installed along with the rest of the dependencies. At this phase in my CI, it is not even referenced/run. Simply another dependency for another task.

## Current behavior

I'm yarn installing my deps at the beginning of a Jenkins job. My setup has been configured for a long time to allow installing of local deps in a checked out node project to my Jenkins machine. Recently, however I've started seeing this error pop up perhaps ~50% of the time:

## Command line output

```
+ yarn
yarn install v1.22.4
[1/4] Resolving packages...

[2/4] Fetching packages...

info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @opendns/css-theme-picker@0.0.8" has incorrect peer dependency "react@^0.14.7 || ^15.0.0".
warning " > react-i18next@8.4.0" has incorrect peer dependency "prop-types@15.6.2".

[4/4] Building fresh packages...

error /var/jenkins/workspace/CUDL/Phase 1 - Preflight/node_modules/yo: Command failed.
Exit code: 1
Command: yodoctor
Arguments: 
Directory: /var/jenkins/workspace/CUDL/Phase 1 - Preflight/node_modules/yo
Output:
Yeoman Doctor
Running sanity checks on your system

module.js:550
    throw err;
    ^

Error: Cannot find module './_basePick'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/jenkins/workspace/CUDL/Phase 1 - Preflight/node_modules/lodash/pick.js:1:78)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by JoshuaKGoldberg** [comment]
`_basePick` is not a file in any Yeoman project. It comes from Lodash, which we can also see is the closest `node_modules` `.js` file in the stack:

> ```plaintext
>     at Object.<anonymous> (/var/jenkins/workspace/CUDL/Phase 1 - Preflight/node_modules/lodash/pick.js:1:78)
> ```

Looks to be a duplicate of https://github.com/lodash/lodash/issues/3753 & others like it: something odd in the user system. 

If anybody has a reproduction, please do file a new issue we can look at (https://antfu.me/posts/why-reproductions-are-required). Cheers! 🎩
