### ISSUE TITLE
yo command create error file permission denied, write

### ISSUE THREAD

**Issue by TechComet** [yeoman/yo#649]
Hi,
yo version
3.1.1

Arguments: 
  /snap/node/2913/bin/node /usr/share/yarn/bin/yarn.js global dir

PATH: 
  /home/techcomet/.npm-global/bin:/home/techcomet/.local/bin

Yarn version: 
  1.22.5

Node version: 
  12.18.3

Platform: 
  linux x64

Trace: 
  Error: EACCES: permission denied, write
      at writeSync (fs.js:679:3)
      at SyncWriteStream._write (internal/fs/sync_write_stream.js:24:3)
      at doWrite (_stream_writable.js:403:12)
      at writeOrBuffer (_stream_writable.js:387:5)
      at SyncWriteStream.Writable.write (_stream_writable.js:318:11)
      at ConsoleReporter._log (/usr/share/yarn/lib/cli.js:96770:17)
      at ConsoleReporter.log (/usr/share/yarn/lib/cli.js:96758:10)
      at dir (/usr/share/yarn/lib/cli.js:36256:14)
      at Object.<anonymous> (/usr/share/yarn/lib/cli.js:25940:25)
      at Generator.next (<anonymous>)

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by JoshuaKGoldberg** [comment]
This doesn't reproduce for me with any `yo` commands locally. And the issue is >4 years old without any activity. Closing out as aged away. But if anybody is seeing this problem, please do post a full reproduction (https://antfu.me/posts/why-reproductions-are-required) - we'd be happy to take a look. Cheers! 🎩
