### ISSUE TITLE
Issue during Codelab tutorial from website (Step 5 npm run serve)

### ISSUE THREAD

**Issue by kadkaad** [yeoman/yo#657]
## My environment

* *OS version/details*: 'Windows 10 64-bit`
* *Node version:* `v14.15.0` 
* *npm version:* `7.6.3` 
* *Version of yo :* `3.1.1` 

## Expected behavior

Following Step 5 of Tutorial "npm run serve" after following all previous steps, expecting to start a local server.

## Current behavior

cmder throws error - local server not starting. Message in CLI:

```
λ npm run serve

> serve
> gulp serve

[16:37:08] Local modules not found in C:\mytodolist
[16:37:08] Try running: npm install
npm ERR! code 1
npm ERR! path C:\mytodolist
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c gulp serve

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\***\AppData\Local\npm-cache\_logs\2021-03-18T15_37_08_862Z-debug.log

```
## Steps to reproduce the behavior

Following Steps 1-4 

## Command line output

npm run serve

Paste your error output over here
```

0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\***\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'serve'
0 verbose cli ]
1 info using npm@7.6.3
2 info using node@v14.15.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:C:\Users\***\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:C:\mytodolist\.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\***\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\***\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 verbose npm-session 6c957d5ecc71dda6
20 timing npm:load Completed in 15ms
21 timing command:run Completed in 370ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (C:\Users\***\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:315:20)
22 verbose stack     at maybeClose (internal/child_process.js:1048:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
23 verbose cwd C:\mytodolist
24 verbose Windows_NT 10.0.19041
25 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\***\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
26 verbose node v14.15.0
27 verbose npm  v7.6.3
28 error code 1
29 error path C:\mytodolist
30 error command failed
31 error command C:\WINDOWS\system32\cmd.exe /d /s /c gulp serve
32 verbose exit 1

**Comment by JoshuaKGoldberg** [comment]
This doesn't reproduce for me when going through the tutorial. 

Looking at the output:

> ```plaintext
> [16:37:08] Local modules not found in C:\mytodolist
> [16:37:08] Try running: npm install
> ```

`npm install` should fix it. Looks like a step was missed. 🙂
