### ISSUE TITLE
 I can't execute yo code properly

### ISSUE THREAD

**Issue by floidenergy** [yeoman/yo#659]
## My environment

* *OS version/details*: `Windows 7 64-bit`
* *Node version:* `v13.14.0`
* *npm version:* `7.8.0` 
* *Version of yo :* `3.1.1`

## my problem

the problem is i cant execut yo on my console even like when i check for the version it returns 3.1.1 which means it's installed correctly but when i execut `yo code` it gives me the current error:

```
C:\Users\floidEnergy\AppData\Roaming\npm\node_modules\yo\node_modules\execa\index.js:347
                throw err;
                ^

Error: Command failed: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
'powershell' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.


    at makeError (C:\Users\floidEnergy\AppData\Roaming\npm\node_modules\←[4myo←[24m\node_modules\←[4mexeca←[24m\index.js:174:9)
    at Function.module.exports.sync (C:\Users\floidEnergy\AppData\Roaming\npm\node_modules\←[4myo←[24m\node_modules\←[4mexeca←[24m\index.js:338:15)
    at windowsRelease (C:\Users\floidEnergy\AppData\Roaming\npm\node_modules\←[4myo←[24m\node_modules\←[4mwindows-release←[24m\index.js:39:19)
    at osName (C:\Users\floidEnergy\AppData\Roaming\npm\node_modules\←[4myo←[24m\node_modules\←[4mos-name←[24m\index.js:39:18)
    at new Insight (C:\Users\floidEnergy\AppData\Roaming\npm\node_modules\←[4myo←[24m\node_modules\←[4minsight←[24m\lib\index.js:37:13)
    at Object.<anonymous> (C:\Users\floidEnergy\AppData\Roaming\npm\node_modules\←[4myo←[24m\lib\cli.js:54:17)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1118:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:982:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:875:14)←[39m {
  code: ←[33m1←[39m,
  stdout: ←[32m''←[39m,
  stderr: ←[32m"'powershell' n'est pas reconnu en tant que commande interne\r\n"←[39m +
    ←[32m'ou externe, un programme ex�cutable ou un fichier de commandes.\r\n'←[39m,
  failed: ←[33mtrue←[39m,
  signal: ←[1mnull←[22m,
  cmd: ←[32m'powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption'←[39m,
  timedOut: ←[33mfalse←[39m
}

```

**Comment by flat-cc** [comment]
what's
