### ISSUE TITLE
Yo fails with node < 12.10.0 lts

### ISSUE THREAD

**Issue by Link631** [yeoman/yo#665]
## My environment

* *OS version/details*:  Windows 10 Enterprise 64 bit
* *Node version:* 8.17.0
* *npm version:* 4.6.1
* *Version of yo :* yo -version gives error: 
* AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:510
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (AppData\Roaming\npm\node_modules\yo\lib\router.js:8:27)

## Expected behavior

yo -version should print the version

## Current behavior

yo -version gives an error

## Steps to reproduce the behavior
1. install latest nodejs msi for nodejs 8.x
2. npm install -g npm@4.6.1
3. npm install -g yo
4. installation runs until sanity checks and breaks with yo -version
## Command line output
Running sanity checks on your system
 
√ No .bowerrc file in home directory
√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ No .yo-rc.json file in home directory
√ Node.js version
√ npm version
{ Error: Command failed: C:\Windows\system32\cmd.exe /s /c "yo "--version""

```
Paste your error output over here
```
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (AppData\Roaming\npm\node_modules\yo\lib\router.js:8:27)

**Comment by mshima** [comment]
Yo supports node >= 12.10.0

**Comment by HappytoGit** [comment]
I know this is closed, but i have no idea where to ask this.

If we need to dev some spfx for SharePoint 2019 (Node 8.x) how do we use yeoman?
