### ISSUE TITLE
TypeError: lookups.flatMap is not a function

### ISSUE THREAD

**Issue by mdogancay** [yeoman/yo#678]
## Type of issue
Bug
----

## My environment

* *OS version/details*: `linux mint 19.3`
* *Node version:* `v10.23.0`
* *npm version:* `7.5.4`
* *Version of yo :* `4.2.0`

## Expected behavior
after install i am running:
$ yo code

## Current behavior

Error output

## Steps to reproduce the behavior
Install
$ yo code
## Command line output

```
$ yo code
/devel/node/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:70
    filePatterns: lookups.flatMap(prefix => [`${prefix}/*/index.ts`, `${prefix}/*/index.js`, `${prefix}/*/index.cjs`, `${prefix}/*/index.mjs`]),
                          ^

TypeError: lookups.flatMap is not a function
    at Environment.resolver.lookup (/devel/node/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:70:27)
    at init (/devel/node/lib/node_modules/yo/lib/cli.js:130:7)
    at pre (/devel/node/lib/node_modules/yo/lib/cli.js:89:3)
    at Object.<anonymous> (/devel/node/lib/node_modules/yo/lib/cli.js:219:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

**Comment by mshima** [comment]
yo@4 requires node 12.

**Comment by jamilhaddadin** [comment]
1-  Remove npm based on npm -g npm
2- Uninstall node.js from the msi file (double click the file then select "Remove")
3- Reinstall node.js my version was 14.9 (using the msi file)
