### ISSUE TITLE
Can't run yo on macos monterey

### ISSUE THREAD

**Issue by dimensi** [yeoman/yo#683]
## Type of issue

I can't start yo because it uses insight, which in turn uses os-name, which in turn uses macos-release. 
Since the system is not known, macos-release crashes with an error. Macos-release made a fix, but now I need to update it everywhere as a dependency.

## My environment

* *OS version/details*: `macos monterey`
* *Node version:* `14.16.0` (run `node --version` in your terminal)
* *Version of yo :* `4.3.0` (run `yo --version` in your terminal)

## Command line output

```
        const [name, version] = nameMap.get(release);
                                ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/Users/dimensi/projects/akit/node_modules/macos-release/index.js:26:26)
    at osName (/Users/dimensi/projects/akit/node_modules/os-name/index.js:21:18)
    at new Insight (/Users/dimensi/projects/akit/node_modules/insight/lib/index.js:37:13)
    at Object.<anonymous> (/Users/dimensi/projects/akit/node_modules/yo/lib/cli.js:54:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

```

**Comment by sarawise** [comment]
I've just run into this as well, tried updating `insight`, `os-name` and `macos-release` to no avail. 

My environment
- OS version/details: `macos monterey`
- Node version: `14.17.0` (run `node --version` in your terminal)
- Version of yo : `3.1.1` (run `yo --version` in your terminal)

Got the same error as @dimensi:
``` 
const [name, version] = nameMap.get(release);
                                ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/usr/local/lib/node_modules/yo/node_modules/macos-release/index.js:26:26)
    at osName (/usr/local/lib/node_modules/yo/node_modules/os-name/index.js:21:18)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:37:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:54:17)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by altjz** [comment]
same issue,  Any updates on this it ?

**Comment by altjz** [comment]
> same issue, Any updates on this it ?

This issue causes by the `[insight](https://www.npmjs.com/package/insight)` is using a outdated [macos-release](https://www.npmjs.com/package/macos-release) (latest version already support, but the `insight` doesn't include the `macos-release` in the package.json dependencies)

```json
"dependencies": {
  "async": "^2.6.2",
  "chalk": "^2.4.2",
  "conf": "^1.4.0",
  "inquirer": "^6.3.1",
  "lodash.debounce": "^4.0.8",
  "os-name": "^3.1.0",
  "request": "^2.88.0",
  "tough-cookie": "^3.0.1",
  "uuid": "^3.3.2"
},
```

## Temporary Solution 

Find the `macos-release` index.js, the error trace would print out in the console.

In my case.

```shell
❯ yo @ubt/ucode
/Users/alex/.config/yarn/global/node_modules/os-name/node_modules/macos-release/index.js:26
	const [name, version] = nameMap.get(release);
	                        ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/Users/alex/.config/yarn/global/node_modules/os-name/node_modules/macos-release/index.js:26:26)
    at osName (/Users/alex/.config/yarn/global/node_modules/os-name/index.js:21:18)
    at new Insight (/Users/alex/.config/yarn/global/node_modules/insight/lib/index.js:37:13)
    at Object.<anonymous> (/Users/alex/.config/yarn/global/node_modules/yo/lib/cli.js:54:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

Check this line, open the `index.js` file
```shell
    at macosRelease (/Users/alex/.config/yarn/global/node_modules/os-name/node_modules/macos-release/index.js:26:26)
```

I add the below line to make it works temporary.

`[21, ['Monterey', '12']],`

```javascript
const nameMap = new Map([
	[21, ['Monterey', '12']], // Here
	[20, ['Big Sur', '11']],
	[19, ['Catalina', '10.15']],
	[18, ['Mojave', '10.14']],
	[17, ['High Sierra', '10.13']],
	[16, ['Sierra', '10.12']],
	[15, ['El Capitan', '10.11']],
	[14, ['Yosemite', '10.10']],
	[13, ['Mavericks', '10.9']],
	[12, ['Mountain Lion', '10.8']],
	[11, ['Lion', '10.7']],
	[10, ['Snow Leopard', '10.6']],
	[9, ['Leopard', '10.5']],
	[8, ['Tiger', '10.4']],
	[7, ['Panther', '10.3']],
	[6, ['Jaguar', '10.2']],
	[5, ['Puma', '10.1']]
]);
```

🍺🍺🍺🍺  cheers!

**Comment by sarawise** [comment]
I tried the fix @altjz suggests when I first experienced this issue and it didn't work for me. I've not found a solution and moved away from this codebase altogether because of it.

**Comment by mshima** [comment]
Latest macos-release is esm only.
Need to catch the exception at 
https://github.com/yeoman/insight/blob/8a3c05dd4da8b4e36fca60862bb0900dfef0aa7d/lib/index.js#L37
And fallback to unknown.

**Comment by altjz** [comment]
> I tried the fix @altjz suggests when I first experienced this issue and it didn't work for me. I've not found a solution and moved away from this codebase altogether because of it.

May be not the same issue, could you provide the log or more information?

**Comment by gandarez** [comment]
Having the same issue here

**Comment by gandarez** [comment]
By doing what @altjz suggested gave me another error

```
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:70
    filePatterns: lookups.flatMap(prefix => [`${prefix}/*/index.ts`, `${prefix}/*/index.js`]),
                          ^

TypeError: lookups.flatMap is not a function
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:70:27)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:130:7)
    at pre (/usr/local/lib/node_modules/yo/lib/cli.js:89:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:219:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

**Comment by gandarez** [comment]
After completely removed `npm uninstall -g yo` and deleted the `yo` folder at `/usr/local/lib/node_modules/` and reinstalled it got working again :)

**Comment by fuss228** [comment]
/opt/homebrew/lib/node_modules/yo/node_modules/macos-release/index.js
Add
    [22, ['Ventura', '13']],

**Comment by likaiweb** [comment]
> ## Type of issue
> I can't start yo because it uses insight, which in turn uses os-name, which in turn uses macos-release. Since the system is not known, macos-release crashes with an error. Macos-release made a fix, but now I need to update it everywhere as a dependency.
> 
> ## My environment
> * _OS version/details_: `macos monterey`
> * _Node version:_ `14.16.0` (run `node --version` in your terminal)
> * _Version of yo :_ `4.3.0` (run `yo --version` in your terminal)
> 
> ## Command line output
> ```
>         const [name, version] = nameMap.get(release);
>                                 ^
> 
> TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
>     at macosRelease (/Users/dimensi/projects/akit/node_modules/macos-release/index.js:26:26)
>     at osName (/Users/dimensi/projects/akit/node_modules/os-name/index.js:21:18)
>     at new Insight (/Users/dimensi/projects/akit/node_modules/insight/lib/index.js:37:13)
>     at Object.<anonymous> (/Users/dimensi/projects/akit/node_modules/yo/lib/cli.js:54:17)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
>     at internal/main/run_main_module.js:17:47
> ```

1. open /usr/local/lib/node_modules/yo/node_modules/macos-release/index.js
2. nameMap add [22, ["Ventura", "13"]]
3. save
4. rerun "yo code"

**Comment by lemuellew** [comment]
```
❯ yo code
/Users/lemuellew/Library/pnpm/global/5/.pnpm/macos-release@2.5.0/node_modules/macos-release/index.js:27
	const [name, version] = nameMap.get(release);
	                        ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/Users/lemuellew/Library/pnpm/global/5/.pnpm/macos-release@2.5.0/node_modules/macos-release/index.js:27:26)
    at osName (/Users/lemuellew/Library/pnpm/global/5/.pnpm/os-name@3.1.0/node_modules/os-name/index.js:21:18)
    at new Insight (/Users/lemuellew/Library/pnpm/global/5/.pnpm/insight@0.10.3/node_modules/insight/lib/index.js:37:13)
    at Object.<anonymous> (/Users/lemuellew/Library/pnpm/global/5/.pnpm/yo@4.3.0/node_modules/yo/lib/cli.js:54:17)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by Nilisha-Cts** [comment]
<img width="1249" alt="Screenshot 2023-04-12 at 1 06 44 PM" src="https://user-images.githubusercontent.com/128121342/231386241-2193dc51-c96a-4abb-b173-bb106eb4aa1c.png">

**Comment by SealinGp** [comment]
> After completely removed `npm uninstall -g yo` and deleted the `yo` folder at `/usr/local/lib/node_modules/` and reinstalled it got working again :)

worked for me

**Comment by shinriyo** [comment]
```

const nameMap = new Map([
        [22, ["Ventura", "13"]],
        [20, ['Big Sur', '11']],
        [19, ['Catalina', '10.15']],
        [18, ['Mojave', '10.14']],
        [17, ['High Sierra', '10.13']],
        [16, ['Sierra', '10.12']],
        [15, ['El Capitan', '10.11']],
        [14, ['Yosemite', '10.10']],
        [13, ['Mavericks', '10.9']],
        [12, ['Mountain Lion', '10.8']],
        [11, ['Lion', '10.7']],
        [10, ['Snow Leopard', '10.6']],
        [9, ['Leopard', '10.5']],
        [8, ['Tiger', '10.4']],
        [7, ['Panther', '10.3']],
        [6, ['Jaguar', '10.2']],
        [5, ['Puma', '10.1']]
]);
```

in `/usr/local/lib/node_modules/yo/node_modules/macos-release/index.js`

**Comment by JoshuaKGoldberg** [comment]
This doesn't reproduce on my computer, and https://github.com/yeoman/yo/issues/683#issuecomment-994770874 + https://github.com/yeoman/yo/issues/683#issuecomment-1008045195 shows the fix. Closing out as aged away. But if someone is still seeing this, please file a new issue with as much system info as possible. Cheers! 🎩
