### ISSUE TITLE
https://registry.npmjs.org/yo-code-dependencies-versions - Not found

### ISSUE THREAD

**Issue by mslinn** [yeoman/yo#738]
## Type of issue
Bug. Unsure if this is a Yeoman problem or not.

First time using `yo`. First thing I did was to **Update your generators**.
Got `404 Not Found - GET https://registry.npmjs.org/yo-code-dependencies-versions - Not found`

## My environment

Does not matter, the URL is missing. Anyway, I will do as asked:

Ubuntu under WSL2 running on Windows 10 64-bit
```shell
$ node --version
v17.3.1

$ npm --version
8.3.1

$ yo --version
4.3.0
```

## Expected behavior

The URL https://registry.npmjs.org/yo-code-dependencies-versions should exist.

## Current behavior

```
$ yo
? ==========================================================================
We're constantly looking for ways to make yo better!
May we anonymously report usage statistics to improve the tool over time?
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== No
? 'Allo Mike! What would you like to do? Update your generators
? Generators to update (Press <space> to select, <a> to toggle all, <i> to invert selection)yo-code-dependencies-versions
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/yo-code-dependencies-versions - Not found
npm ERR! 404
npm ERR! 404  'yo-code-dependencies-versions@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mslinn/.npm/_logs/2022-03-01T19_25_37_200Z-debug-0.log

I've just updated your generators. Remember, you can update
a specific generator with npm by running:

    npm install -g generator-_______
```
Here is the log:
```
$ cat  /home/mslinn/.npm/_logs/2022-03-01T19_25_37_200Z-debug-0.log
0 verbose cli [
0 verbose cli   '/home/mslinn/.nvm/versions/node/v17.3.1/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--global',
0 verbose cli   'yo-code-dependencies-versions'
0 verbose cli ]
1 info using npm@8.3.1
2 info using node@v17.3.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 5ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 6ms
10 timing config:load:file:/home/mslinn/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:validate Completed in 1ms
15 timing config:load:credentials Completed in 2ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 25ms
18 timing npm:load:configload Completed in 25ms
19 timing npm:load:setTitle Completed in 1ms
20 timing config:load:flatten Completed in 5ms
21 timing npm:load:display Completed in 8ms
22 verbose logfile /home/mslinn/.npm/_logs/2022-03-01T19_25_37_200Z-debug-0.log
23 timing npm:load:logFile Completed in 7ms
24 timing npm:load:timers Completed in 0ms
25 timing npm:load:configScope Completed in 0ms
26 timing npm:load Completed in 43ms
27 timing arborist:ctor Completed in 1ms
28 silly logfile start cleaning logs, removing 2 files
29 timing idealTree:init Completed in 7ms
30 timing idealTree:userRequests Completed in 5ms
31 silly idealTree buildDeps
32 silly fetch manifest yo-code-dependencies-versions@*
33 http fetch GET 404 https://registry.npmjs.org/yo-code-dependencies-versions 363ms (cache skip)
34 http fetch GET 404 https://registry.npmjs.org/yo-code-dependencies-versions 405ms (cache skip)
35 silly placeDep ROOT yo-code-dependencies-versions@ OK for:  want: *
36 timing idealTree:#root Completed in 781ms
37 timing idealTree:node_modules/yo-code-dependencies-versions Completed in 0ms
38 timing idealTree:buildDeps Completed in 782ms
39 timing idealTree:fixDepFlags Completed in 0ms
40 timing idealTree Completed in 797ms
41 timing command:install Completed in 820ms
42 verbose stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/yo-code-dependencies-versions - Not found
42 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
42 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
42 verbose stack     at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1066:19)
42 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:935:11)
42 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
42 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:149:5)
42 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:157:5)
42 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:66:5)
43 verbose statusCode 404
44 verbose pkgid yo-code-dependencies-versions@*
45 verbose cwd /mnt/f/work/jekyll/redirect_generator
46 verbose Linux 5.10.60.1-microsoft-standard-WSL2
47 verbose argv "/home/mslinn/.nvm/versions/node/v17.3.1/bin/node" "/usr/local/bin/npm" "install" "--global" "yo-code-dependencies-versions"
48 verbose node v17.3.1
49 verbose npm  v8.3.1
50 error code E404
51 error 404 Not Found - GET https://registry.npmjs.org/yo-code-dependencies-versions - Not found
52 error 404
53 error 404  'yo-code-dependencies-versions@*' is not in this registry.
54 error 404 You should bug the author to publish it (or use the name yourself!)
55 error 404
55 error 404 Note that you can also install from a
56 error 404 tarball, folder, http url, or git url.
57 verbose exit 1
58 timing npm Completed in 1158ms
59 verbose unfinished npm timer reify 1646162737527
60 verbose unfinished npm timer reify:loadTrees 1646162737545
61 verbose code 1
62 error A complete log of this run can be found in:
62 error     /home/mslinn/.npm/_logs/2022-03-01T19_25_37_200Z-debug-0.log
```

## Steps to reproduce the behavior

Just run `yo` and ask to update the generators, as shown above.

**Comment by mslinn** [comment]
I think this is a yo-code problem, not yours. Closing
