### ISSUE TITLE
Yeoman broken after install.

### ISSUE THREAD

**Issue by stuartstein777** [yeoman/yo#788]
## Type of issue

Yeoman is broken after install.

----

## My environment

* *OS version/details*: Ubuntu 20.04.6 LTS
* *Node version:* 10.19.0
* *npm version:* 6.14.4
* *Version of yo :* NO idea, it's broken after install and I can't even run yo --version

## Expected behavior

That Yeoman works.

## Current behavior

Installed yo with `sudo npm install --global yo`

Any yo command just results in :

```
/usr/local/lib/node_modules/yo/node_modules/minimatch/dist/cjs/index.js:208
    options;
           ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/minimatch/dist/cjs/index-cjs.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

```

Tried `sudo yo --version` and I get the same error.

## Command line output

```
/usr/local/lib/node_modules/yo/node_modules/minimatch/dist/cjs/index.js:208
    options;
           ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/minimatch/dist/cjs/index-cjs.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

```

**Comment by stuartstein777** [comment]
Uninstalled and reinstalled node / npm, now my npm version is 9.7.1 and yo works :)
