### ISSUE TITLE
microsoft/sharepoint generator

### ISSUE THREAD

**Issue by MoriaNuri** [yeoman/yo#798]
Hey,
I try run yo @microsoft/sharepoint

I get "Error
Current environment doesn't provides some necessary feature this generator needs."

yesterday before your update the version its work

## My environment
v16.13.0 node

**Comment by mshima** [comment]
Try to reinstall the `@microsoft/sharepoint` generator

**Comment by baender** [comment]
I get the same error when trying to use it with @microsoft/sharepoint.

OS: macOS 14.0
Node: 18.18.2 (v16 and v18 are supported by Sharepoint Framework v1.18.*)

Here is the debug output:

```
yo @microsoft/sharepoint --debug
Error @microsoft/sharepoint --debug 

Error: Current environment doesn't provides some necessary feature this generator needs.
    at new Generator (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/yeoman-generator/lib/index.js:259:13)
    at new BaseGenerator (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/lib/common/BaseGenerator.js:44:9)
    at new AppGenerator (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/lib/generators/app/index.js:61:9)
    at FullEnvironment.instantiate (file:///usr/local/lib/node_modules/yo/node_modules/yeoman-environment/dist/environment-base.js:252:27)
    at FullEnvironment.create (file:///usr/local/lib/node_modules/yo/node_modules/yeoman-environment/dist/environment-base.js:246:21)
    at async FullEnvironment.run (file:///usr/local/lib/node_modules/yo/node_modules/yeoman-environment/dist/environment-full.js:307:27)
    at async init (/usr/local/lib/node_modules/yo/lib/cli.js:168:5)
    at async pre (/usr/local/lib/node_modules/yo/lib/cli.js:83:3)
    at async /usr/local/lib/node_modules/yo/lib/cli.js:193:3

```

**Comment by mshima** [comment]
As workaround install v4 `npm install yo@4`.
