### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream'

### ISSUE THREAD

**Issue by danielbrendel** [yeoman/yo#805]
## Type of issue

I just installed yo along with generator code in order to create custom syntax. However I get an error when I want to run yo:

```
C:\Users\Danny\Desktop\test>yo --help
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from C:\Users\Danny\AppData\Roaming\npm\node_modules\yo\node_modules\mem-fs\dist\index.js
    at packageResolve (internal/modules/esm/resolve.js:655:9)
    at moduleResolve (internal/modules/esm/resolve.js:696:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36)
```
This happens for any yo command I try except --version.

----

## My environment

* *OS version/details*: `Windows 11 64-Bit`
* *Node version:* `v14.16.1`
* *npm version:* `6.14.12`
* *Version of yo :* `5.0.0`

## Expected behavior

Show yo help screen / package creation dialog.

## Current behavior

Fails with exception.

## Steps to reproduce the behavior

Install yo globally:
```
npm i -g yo generator-code
```
Run yo command without admin privilegues.

## Command line output

```
C:\Users\Danny\Desktop\test>yo --help
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from C:\Users\Danny\AppData\Roaming\npm\node_modules\yo\node_modules\mem-fs\dist\index.js
    at packageResolve (internal/modules/esm/resolve.js:655:9)
    at moduleResolve (internal/modules/esm/resolve.js:696:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36)

C:\Users\Danny\Desktop\test>yo code
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from C:\Users\Danny\AppData\Roaming\npm\node_modules\yo\node_modules\mem-fs\dist\index.js
    at packageResolve (internal/modules/esm/resolve.js:655:9)
    at moduleResolve (internal/modules/esm/resolve.js:696:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36)
```

**Comment by danielbrendel** [comment]
Updating node/npm fixed the issue. Would be better tho if the installation would fail with a proper hint.
